name = "all"
kind = "marker-team"

[people]
leads = []
members = []
include-all-team-members = true

[[github]]
orgs = ["rust-lang"]

[[lists]]
address = "all@rust-lang.org"

[[lists]]
address = "team@rust-lang.org"

[[lists]]
address = "underhanded@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-underhanded@googlegroups.com",
]

[[lists]]
address = "verification@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-verification@googlegroups.com",
]

[[zulip-groups]]
name = "T-all"
# Exclude the following people from the Zulip group for grandfathering purposes,
# where previously we didn't require all project team members to have Zulip IDs
# (since there wasn't a `T-all` Zulip group previously).
excluded-people = [
    "U007D",
    "andrewpollack",
    "bnchi",
    "celaus",
    "opeolluwa",
]

# Private channel with all team members, so that we can have an easy way of reaching them.
[[zulip-streams]]
name = "all/private"
# Exclude the following people from the Zulip stream for grandfathering purposes,
# where previously we didn't require all project team members to have Zulip IDs.
excluded-people = [
    "U007D",
    "andrewpollack",
    "arshiamufti",
    "bnchi",
    "celaus",
    "opeolluwa",
]
