name = "all"
kind = "marker-team"

[people]
leads = []
members = []
include-all-team-members = true

[[github]]
orgs = ["rust-lang"]

[[lists]]
address = "all@rust-lang.org"

[[lists]]
address = "team@rust-lang.org"

[[lists]]
address = "underhanded@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-underhanded@googlegroups.com",
]

[[lists]]
address = "verification@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-verification@googlegroups.com",
]

[[zulip-groups]]
name = "T-all"

# Private channel with all team members, so that we can have an easy way of reaching them.
# Also includes Rust Foundation staff, for any relevant non-public communication.
[[zulip-streams]]
name = "all/private"
extra-teams = [
    "foundation-staff",
]
