name = "alumni"

[people]
leads = []
members = [
    "Gankra",
    "Aatch",
    "alercah",
    "arielb1",
    "bkoropoff",
    "booyaa",
    "brson",
    "bstrie",
    "dotdash",
    "dwijnand",
    "edunham",
    "erickt",
    "huonw",
    "jseyfried",
    "pcwalton",
    "peschkaj",
    "tomprince",
    "wycats",
]

[website]
name = "Rust team alumni"
description = "enjoying a leisurely retirement"
weight = -1000
