# DEPRECATED: Do not add new members to this team, instead add to `people.alumni`
# in the team's file or create a new `people.alumni` key and add the
# person's name there instead.
name = "alumni"

[people]
leads = []
members = [
    "Aatch",
    "Gankra",
    "Kimundi",
    "MajorBreakfast",
    "QuietMisdreavus",
    "TimNN",
    "alercah",
    "arielb1",
    "aturon",
    "birkenfeld",
    "bkoropoff",
    "booyaa",
    "brson",
    "dotdash",
    "dwijnand",
    "edunham",
    "erickt",
    "frewsxcv",
    "gnunicorn",
    "huonw",
    "jonathandturner",
    "jseyfried",
    "levex",
    "niconii",
    "pcwalton",
    "peschkaj",
    "rpjohnst",
    "tomprince",
    "valgrimm",
    "whitequark",
    "wycats",
]
# Temporary key that includes all members listed as alumni in the individual
# teams. This is needed while we migrate away from the alumni team.
include-all-alumni = true

[website]
name = "Rust team alumni"
description = "Enjoying a leisurely retirement"
weight = -1000
