name = "cargo"
subteam-of = "devtools"

[people]
leads = ["ehuss"]
members = [
    "alexcrichton",
    "Eh2406",
    "ehuss",
    "joshtriplett",
    "nrc",
]

[permissions]
bors.rust.review = true
bors.cargo.review = true

[github]
orgs = ["rust-lang", "rust-lang-nursery"]

[rfcbot]
label = "T-cargo"
name = "Cargo"
ping = "rust-lang/cargo"

[website]
name = "Cargo team"
description = "design and implementation of Cargo"
discord-invite = "https://discord.gg/aEbd4eT"
discord-name = "#cargo"

[[lists]]
address = "cargo@rust-lang.org"
