name = "clippy"
subteam-of = "devtools"

[people]
leads = ["Manishearth", "flip1995"]
members = [
    "llogiq",
    "Manishearth",
    "matthiaskrgr",
    "flip1995",
    "giraffate",
    "xFrednet",
    "Alexendoo",
    "dswij",
    "Jarcho",
    "blyxyas",
    "Centri3",
]
alumni = [
    "ebroto",
    "yaahc",
    "oli-obk",
    "killercup",
    "mcarton",
    "phansch",
    "camsteffen",
    "birkenfeld",
]

[permissions]
perf = true
bors.clippy.review = true
bors.rust.review = true
dev-desktop = true

[[github]]
orgs = ["rust-lang"]

[website]
name = "Clippy team"
description = "Designing and implementing the Clippy linter"
zulip-stream = "clippy"
repo = "https://github.com/rust-lang/rust-clippy"

[[lists]]
address = "clippy@rust-lang.org"

[[zulip-groups]]
name = "T-clippy"
