name = "clippy"
subteam-of = "devtools"

[people]
leads = ["Manishearth", "oli-obk"]
members = [
    "llogiq",
    "killercup",
    "Manishearth",
    "oli-obk",
    "matthiaskrgr",
    "phansch",
    "mikerite",
    "flip1995",
    "mcarton",
    "yaahc",
]

[permissions]
bors.clippy.review = true

[github]
orgs = ["rust-lang"]

[website]
name = "Clippy"
description = "design and implementation of the Clippy linter"
discord-invite = "https://discord.gg/vNNtpyD"
discord-name = "#clippy"
