name = "community-rustbridge"
subteam-of = "community"

[people]
leads = ["fmoko"]
members = [
    "fmoko",
    "ashleygwilliams",
    "technetos",
    "arshiamufti",
    "spacekookie",
    "sebasmagri",
    "mattgathu",
]

[website]
name = "RustBridge team"
description = "An inclusive educational initiative focused on bringing underrepresented groups into Rust."
repo = "https://github.com/rustbridge/team"
discord-invite = "https://discord.gg/cj5HMXA"
discord-name = "#rustbridge"

[github]
orgs = ["rust-lang"]
