name = "community-survey"
subteam-of = "community"

[people]
leads = ["Kobzol", "apiraino"]
members = ["graciegregory", "Kobzol", "apiraino"]
alumni = [
    "Manishearth",
    "nikomatsakis",
    "nrc",
    "sophiajt",
    "yaahc",
    "rylev",
]

[website]
name = "Survey team"
description = "Running, analysing, and presenting the community survey"
repo = "https://github.com/rust-lang/surveys"

[[github]]
orgs = ["rust-lang"]

[[lists]]
address = "surveys@rust-lang.org"
