name = "community"

[people]
leads = []
members = [
    "skade",
    "Manishearth",
    "sebasmagri",
    "ashleygwilliams",
    "badboy",
    "technetos",
    "JohnTitor",
    "nellshamrell",
]
alumni = [
    "fmoko",
]

[website]
name = "Community team"
description = "Coordinating and supporting events, content creation, and the RustBridge program, as well as conducting community surveys"
email = "community@rust-lang.org"
repo = "https://github.com/rust-community/team"
discord-invite = "https://discord.gg/KskHZGT"
discord-name = "#community-team"

[[github]]
orgs = ["rust-lang"]

[[lists]]
address = "community@rust-lang.org"
extra-teams = [
    "community-content",
    "community-events",
    "community-survey",
    "community-localization",
]
extra-emails = [
    "rust-community@googlegroups.com",
]

[[lists]]
address = "community-team@rust-lang.org"
extra-teams = [
    "community-content",
    "community-events",
    "community-survey",
    "community-localization",
]
extra-emails = [
    "rust-community@googlegroups.com",
]

[[lists]]
address = "reach@rust-lang.org"
include-team-members = false
extra-people = [
    "ashleygwilliams",
    "carols10cents",
    "aidanhs",
]
extra-emails = [
    "dhosfelt@mozilla.com",
]

[[lists]]
address = "rustbridge@rust-lang.org"
include-team-members = false
extra-people = [
    "fmoko",
    "ashleygwilliams",
    "arshiamufti"
]

[[lists]]
address = "rust-all-hands@rust-lang.org"
include-team-members = false
extra-people = [
    "Manishearth",
    "nikomatsakis",
    "Dylan-DPC",
    "spastorino",
    "skade",
]

[discord-role]
name = "community-team"
role-id = 474953197354483714
color = "#c27c0e"
