name = "community-content"
subteam-of = "community"

[people]
leads = []
members = [
    "adityac8",
    "nasa42",
    "skade",
    "wezm",
]

[website]
name = "Content team"
description = "Collecting and developing community content"
repo = "https://github.com/rust-community/content-team"
discord-invite = "https://discord.gg/b7a22kw"
discord-name = "#content-team"

[github]
orgs = ["rust-lang"]
