name = "community-survey"
subteam-of = "community"

[people]
leads = ["Manishearth"]
members = [
    "Manishearth",
]

[website]
name = "Survey team"
description = "Running, analysing, and presenting the community survey."
