name = "community-events"
subteam-of = "community"

[people]
leads = []
members = [
    "mattgathu",
    "celaus",
    "flaki",
    "badboy",
    "Manishearth",
    "JohnTitor",
]
alumni = [
    "skade",
]

[website]
name = "Events team"
description = "Supporting and organizing community events"
repo = "https://github.com/rust-community/events-team"
discord-invite = "https://discord.gg/cj5HMXA"
discord-name = "#events"

[[github]]
orgs = ["rust-lang"]
