name = "compiler"

[people]
leads = ["nikomatsakis"]
members = [
    "cramertj",
    "eddyb",
    "estebank",
    "nagisa",
    "oli-obk",
    "petrochenkov",
    "pnkfelix",
    "nikomatsakis",
    "michaelwoerister",
    "varkor",
    "Zoxc",
]

[permissions]
perf = true
crater = true
bors.rust.review = true

[rfcbot]
label = "T-compiler"
name = "Compiler"
ping = "rust-lang/compiler"

[website]
name = "Compiler team"
repo = "http://github.com/rust-lang/compiler-team"
description = "compiler internals, optimizations"

[[lists]]
address = "compiler@rust-lang.org"
extra-people = [
    "arielb1",
    "jseyfried",
]

[[lists]]
address = "compiler-team@rust-lang.org"
extra-people = [
    "arielb1",
    "jseyfried",
]
