name = "compiler"

[people]
leads = ["wesleywiser", "pnkfelix"]
members = [
    "Aaron1011",
    "cjgillot",
    "davidtwco",
    "eddyb",
    "estebank",
    "lcnr",
    "michaelwoerister",
    "nagisa",
    "oli-obk",
    "petrochenkov",
    "pnkfelix",
    "nikomatsakis",
    "matthewjasper",
    "wesleywiser",
]
alumni = [
    "cramertj",
    "dotdash",
    "nrc",
    "varkor",
    "Zoxc",
]

[permissions]
perf = true
crater = true
bors.rust.review = true
bors.miri.review = true
bors.measureme.review = true

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[rfcbot]
label = "T-compiler"
name = "Compiler"
ping = "rust-lang/compiler"

[website]
name = "Compiler team"
repo = "http://github.com/rust-lang/compiler-team"
description = "Developing and managing compiler internals and optimizations"
zulip-stream = "t-compiler"

[[lists]]
address = "compiler-private@rust-lang.org"

[[lists]]
address = "compiler@rust-lang.org"
extra-teams = ["compiler-contributors"]
extra-people = [
    "arielb1",
    "jseyfried",
]

[[lists]]
address = "compiler-team@rust-lang.org"
extra-teams = ["compiler-contributors"]
extra-people = [
    "arielb1",
    "jseyfried",
]
