name = "compiler"
top-level = true

[people]
leads = ["davidtwco", "wesleywiser"]
members = [
    "alexcrichton",
    "apiraino",
    "b-naber",
    "bjorn3",
    "BoxyUwU",
    "camelid",
    "chenyukang",
    "ChrisDenton",
    "cjgillot", 
    "compiler-errors",
    "cuviper",
    "davidtwco",
    "DianQK",
    "durin42",
    "eholk",
    "est31",
    "estebank",
    "fee1-dead",
    "flodiebold",
    "fmease", 
    "jackh726",
    "jieyouxu",
    "jswrenn",
    "lcnr",
    "lqd",
    "lukas-code",
    "m-ou-se",
    "Mark-Simulacrum",
    "matthewjasper",
    "Nadrieril",
    "nagisa",
    "nikic",
    "nikomatsakis",
    "Noratrieb",
    "nnethercote",
    "oli-obk",
    "petrochenkov",
    "pnkfelix",
    "RalfJung",
    "rcvalle",
    "saethlin",
    "scottmcm",
    "SparrowLii",
    "spastorino",
    "TaKO8Ki",
    "tgross35",
    "the8472",
    "tmandry",
    "tmiasko",
    "Urgau",
    "WaffleLapkin",
    "wesleywiser",
    "workingjubilee",
    "Zalathar",
]
alumni = [
    "Aaron1011",
    "Aatch",
    "arielb1",
    "bkoropoff",
    "Centril",
    "cramertj",
    "dotdash",
    "ecstatic-morse",
    "eddyb",
    "jseyfried",
    "LeSeulArtichaut",
    "matklad",
    "michaelwoerister",
    "nrc",
    "scalexm",
    "varkor",
    "Xanewok",
    "zackmdavis",
    "Zoxc",
]

[permissions]
perf = true
crater = true
dev-desktop = true
bors.rust.review = true

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[website]
name = "Compiler team"
repo = "http://github.com/rust-lang/compiler-team"
description = "Developing and managing compiler internals and optimizations"
zulip-stream = "t-compiler"

[[lists]]
address = "compiler-private@rust-lang.org"

[[lists]]
address = "compiler@rust-lang.org"

[[lists]]
address = "compiler-team@rust-lang.org"

[[lists]]
address = "compiler-and-subteams@rust-lang.org"
include-subteam-members = true

[[zulip-groups]]
name = "T-compiler"

[[zulip-groups]]
name = "T-compiler/meeting"
include-team-members = false
extra-people = [
    "davidtwco",
    "wesleywiser",
    "apiraino",
    "bjorn3",
    "SparrowLii",
    "estebank",
    "BoxyUwU",
    "jieyouxu",
    "jswrenn",
    "spastorino",
    "tmiasko"
]

[[zulip-streams]]
name = "t-compiler/contrib-private"
