name = "compiler-contributors"
subteam-of = "compiler"

[people]
leads = []
members = [
    "apiraino",
    "b-naber",
    "bjorn3",
    "BoxyUwU",
    "chenyukang",
    "cuviper",
    "durin42",
    "eholk",
    "est31",
    "fee1-dead",
    "flodiebold",
    "fmease",
    "jieyouxu",
    "lqd",
    "Mark-Simulacrum",
    "Nadrieril",
    "Nilstrieb",
    "nikic",
    "nikomatsakis",
    "nnethercote",
    "RalfJung",
    "saethlin",
    "SparrowLii",
    "spastorino",
    "the8472",
    "tmandry",
    "tmiasko",
    "TaKO8Ki",
    "Urgau",
    "WaffleLapkin",
]
alumni = [
    "Centril",
    "LeSeulArtichaut",
    "zackmdavis",
    "matklad",
    "ecstatic-morse",
    "scalexm",
    "varkor",
    "Xanewok",
]

[permissions]
perf = true
crater = true
dev-desktop = true
bors.rust.review = true

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]
extra-teams = ["compiler"]

[website]
name = "Compiler team contributors"
repo = "http://github.com/rust-lang/compiler-team"
description = "Contributing to the Rust compiler on a regular basis"
