name = "compiler-fcp"
subteam-of = "compiler"

[people]
leads = []
members = [
    "cjgillot",
    "davidtwco",
    "estebank",
    "jieyouxu",
    "Mark-Simulacrum",
    "matthewjasper",
    "nagisa",
    "oli-obk",
    "petrochenkov",
    "SparrowLii",
    "spastorino",
    "TaKO8Ki",
    "wesleywiser",
]
alumni = [
    "compiler-errors",
    "Noratrieb",
]

[rfcbot]
label = "T-compiler"
name = "Compiler"
ping = "rust-lang/compiler-fcp"

[website]
name = "Compiler FCP team"
description = "Compiler team members with responsibility for signing off on major compiler changes"
repo = "http://github.com/rust-lang/compiler-team"
zulip-stream = "t-compiler"

