name = "compiler-contributors"
subteam-of = "compiler"

[people]
leads = []
members = [
  "Aaron1011",
  "bjorn3",
  "cjgillot",
  "cuviper",
  "ecstatic-morse",
  "flodiebold",
  "jonas-schievink",
  "lqd",
  "Mark-Simulacrum",
  "matklad",
  "michaelwoerister",
  "Nadrieril",
  "nikic",
  "nnethercote",
  "RalfJung",
  "scalexm",
  "spastorino",
  "tmandry",
  "Xanewok",
  "zackmdavis",
]
alumni = [
    "Centril",
]

[permissions]
perf = true
crater = true
bors.rust.review = true

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]
extra-teams = ["compiler"]

[website]
name = "Compiler team contributors"
repo = "http://github.com/rust-lang/compiler-team"
description = "Folks who contribute to the Rust compiler on a regular basis"
