name = "compiler-contributors"
subteam-of = "compiler"

[people]
leads = []
members = [
  "bjorn3",
  "BoxyUwU",
  "compiler-errors",
  "cuviper",
  "ecstatic-morse",
  "eholk",
  "fee1-dead",
  "flodiebold",
  "jackh726",
  "jonas-schievink",
  "lqd",
  "Mark-Simulacrum",
  "matklad",
  "Nadrieril",
  "nikic",
  "nnethercote",
  "RalfJung",
  "scalexm",
  "spastorino",
  "the8472",
  "tmandry",
  "tmiasko",
  "TaKO8Ki",
  "varkor",
  "Xanewok",
  "zackmdavis",
]
alumni = [
    "Centril",
    "LeSeulArtichaut",
]

[permissions]
perf = true
crater = true
dev-desktop = true
bors.rust.review = true

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]
extra-teams = ["compiler"]

[website]
name = "Compiler team contributors"
repo = "http://github.com/rust-lang/compiler-team"
description = "Contributing to the Rust compiler on a regular basis"
