name = "core"

[people]
leads = []
members = [
    "Mark-Simulacrum",
    "aidanhs",
    "rylev",
    "badboy",
    "jntrnr",
]
alumni = [
    "nrc",
    "carols10cents",
    "nikomatsakis",
    "Manishearth",
    "skade",
    "steveklabnik",
    "pietroalbini",
    "ashleygwilliams",
]

[permissions]
bors.rust.review = true
bors.team.review = true

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[rfcbot]
label = "T-core"
name = "Core"
ping = "rust-lang/core"

[website]
name = "Core team"
description = "Managing the overall direction of Rust, subteam leadership, and any cross-cutting issues"
email = "core@rust-lang.org"
weight = 1000

[[lists]]
address = "core@rust-lang.org"

[[lists]]
address = "core-private@rust-lang.org"

[[lists]]
address = "core-team@rust-lang.org"

[[lists]]
address = "user-logos@rust-lang.org"

[[lists]]
address = "legal@crates.io"

[[discord-roles]]
name = "core-team"
color = "#3498db"

