name = "core-observers"
subteam-of = "core"

[people]
leads = []
members = [
    "skade",
]

[[github]]
orgs = ["rust-lang"]

[permissions]
bors.rust.review = true

[website]
name = "Core team observers"
description = "Observers on the core team"
