name = "core"

[people]
leads = []
members = [
    "Mark-Simulacrum",
    "aidanhs",
    "ashleygwilliams",
    "carols10cents",
    "nikomatsakis",
    "nrc",
    "pietroalbini",
    "steveklabnik",
    "Manishearth",
]

[permissions]
bors.rust.review = true
bors.team.review = true

[rfcbot]
label = "T-core"
name = "Core"
ping = "rust-lang/core"

[website]
name = "Core team"
description = "Direction of the project, subteam leadership, cross-cutting concerns."
email = "core@rust-lang.org"
weight = 1000

[[lists]]
address = "core@rust-lang.org"
extra-teams = ["core-observers"]

[[lists]]
address = "core-private@rust-lang.org"

[[lists]]
address = "core-team@rust-lang.org"
extra-teams = ["core-observers"]

[[lists]]
address = "user-logos@rust-lang.org"

[[lists]]
address = "legal@crates.io"

[[lists]]
address = "trademark@rust-lang.org"
include-team-members = false
extra-people = ["nikomatsakis"]

[[lists]]
address = "mediation@rust-lang.org"
include-team-members = false
extra-people = [
    "Mark-Simulacrum",
    "aidanhs",
    "ashleygwilliams",
    "nikomatsakis",
    "nrc",
    "steveklabnik",
    "Manishearth",
]

[[lists]]
address = "privacy@rust-lang.org"
