name = "crates-io"

[people]
leads = ["jtgeibel", "sgrif"]
members = [
    "carols10cents",
    "ashleygwilliams",
    "sgrif",
    "jtgeibel",
    "withoutboats",
    "joshtriplett",
    "ishitatsuyuki",
    "steveklabnik",
    "pietroalbini",
    "locks",
    "Turbo87",
    "smarnach",
    "JohnTitor",
]

[permissions]
bors.crates_io.review = true

[github]
orgs = ["rust-lang"]

[rfcbot]
label = "T-crates-io"
name = "Crates.io"
ping = "rust-lang/crates-io"

[website]
name = "Crates.io team"
description = "Managing operations, development, and official policies for crates.io"
discord-invite = "https://discord.gg/Rbq8W5K"
discord-name = "#crates-io"

[[lists]]
address = "crates-io@rust-lang.org"

[[lists]]
address = "help@crates.io"
include-team-members = false
extra-people = [
    "carols10cents",
    "ashleygwilliams",
    "sgrif",
    "pietroalbini",
    "jtgeibel",
]
