name = "crates-io"

[people]
leads = ["jtgeibel", "Turbo87"]
members = [
    "carols10cents",
    "jtgeibel",
    "Turbo87",
    "JohnTitor",
    "LawnGnome",
    "mdtro",
]
alumni = [
    "steveklabnik",
    "ashleygwilliams",
    "withoutboats",
    "joshtriplett",
    "ishitatsuyuki",
    "sgrif",
    "nellshamrell",
    "hi-rustin",
    "pietroalbini",
    "smarnach",
    "pichfl",
    "locks",
]

[permissions]
bors.crates-io.review = true

[[github]]
orgs = ["rust-lang", "conduit-rust"]

[rfcbot]
label = "T-crates-io"
name = "Crates.io"
ping = "rust-lang/crates-io"

[website]
name = "Crates.io team"
description = "Managing operations, development, and official policies for crates.io"
zulip-stream = "t-crates-io"
repo = "https://github.com/rust-lang/crates.io"

[[lists]]
address = "crates-io@rust-lang.org"

[[lists]]
address = "help@crates.io"
include-team-members = false
extra-emails = [
    "crates.io@rust-lang.zendesk.com",
]
extra-people = [
    "carols10cents",
    "jtgeibel",
]

[[zulip-groups]]
name = "T-crates-io"
