name = "crates-io"

[people]
leads = ["ashleygwilliams", "sgrif", "jtgeibel"]
members = [
    "carols10cents",
    "ashleygwilliams",
    "sgrif",
    "jtgeibel",
    "withoutboats",
    "joshtriplett",
    "ishitatsuyuki",
    "steveklabnik",
    "pietroalbini",
    "locks",
    "Turbo87",
    "smarnach",
]

[github]
orgs = ["rust-lang"]

[rfcbot]
label = "T-crates-io"
name = "Crates.io"
ping = "rust-lang/crates-io"

[website]
name = "Crates.io team"
description = "Management of operations, development, and policies for crates.io."
discord-invite = "https://discord.gg/Rbq8W5K"
discord-name = "#crates-io"

[[lists]]
address = "crates-io@rust-lang.org"

[[lists]]
address = "help@crates.io"
include-team-members = false
extra-people = [
    "carols10cents",
    "ashleygwilliams",
    "sgrif",
    "pietroalbini",
]
