name = "crates-io"

[people]
leads = ["jtgeibel", "Turbo87"]
members = [
    "carols10cents",
    "jtgeibel",
    "pichfl",
    "locks",
    "Turbo87",
    "smarnach",
    "JohnTitor",
]
alumni = [
    "steveklabnik",
    "ashleygwilliams",
    "withoutboats",
    "joshtriplett",
    "ishitatsuyuki",
    "sgrif",
    "nellshamrell",
    "hi-rustin",
    "pietroalbini",
]

[permissions]
bors.crates-io.review = true
crates-io-ops-bot.staging-crates-io = true

[[github]]
orgs = ["rust-lang", "conduit-rust"]

[rfcbot]
label = "T-crates-io"
name = "Crates.io"
ping = "rust-lang/crates-io"

[website]
name = "Crates.io team"
description = "Managing operations, development, and official policies for crates.io"
discord-invite = "https://discord.gg/Rbq8W5K"
discord-name = "#crates-io-team"

[[lists]]
address = "crates-io@rust-lang.org"

[[lists]]
address = "help@crates.io"
include-team-members = false
extra-emails = [
    "crates.io@rust-lang.zendesk.com",
]
extra-people = [
    "carols10cents",
    "pietroalbini",
    "jtgeibel",
]
