name = "devtools"

[people]
leads = ["Manishearth"]
members = ["Manishearth", "Xanewok", "fitzgen", "GuillaumeGomez", "oli-obk", "kinnison", "ehuss"]
alumni = ["nrc", "killercup"]

[rfcbot]
label = "T-dev-tools"
name = "Dev tools"
ping = "rust-lang/dev-tools"

[website]
page = "dev-tools"
name = "Dev tools team"
email = "tools@rust-lang.org"
description = "Contributing to and creating the Rust development tools"
repo = "https://github.com/rust-dev-tools/dev-tools-team"
zulip-stream = "t-devtools"

[[github]]
orgs = ["rust-lang", "rust-dev-tools"]

[[lists]]
address = "tools@rust-lang.org"

[[lists]]
address = "tools-all@rust-lang.org"
extra-teams = [
    "cargo",
    "clippy",
    "ides",
    "rustdoc",
    "wg-bindgen",
    "wg-rustfmt",
    "wg-rustup",
    "wg-rustfix",
]
extra-people = ["spacekookie"]

[[lists]]
address = "dev-tools@rust-lang.org"

[[lists]]
address = "rust-dev-tools@rust-lang.org"

[[lists]]
address = "tools-team@rust-lang.org"
