name = "docs-rs"
subteam-of = "devtools"

[people]
leads = ["syphar"]
members = [
    "GuillaumeGomez",
    "Nemo157",
    "jyn514",
    "syphar",
    "Byron",
    "jsha",
]
alumni = [
    "Kixiron",
    "onur",
    "pietroalbini",
]

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[rfcbot]
label = "T-docs-rs"
name = "Docs.rs"
ping = "rust-lang/docs-rs"

[website]
name = "Docs.rs team"
description = "Docs.rs, the documentation hosting service for crates"
zulip-stream = "t-docs-rs"
repo = "https://github.com/rust-lang/docs.rs"

[[lists]]
address = "docs-rs@rust-lang.org"

[[lists]]
address = "help@docs.rs"

[[zulip-groups]]
name = "T-docs-rs"
