name = "emacs"
kind = "marker-team"

[people]
leads = []
members = [
    "pnkfelix",
    "MicahChalmer",
    "tromey",
    "brotzeit",
    "jimblandy",
    "psibi",
    "jcs090218",
]

[[github]]
orgs = ["rust-lang"]
