name = "fuchsia"
kind = "marker-team"

[people]
leads = []
members = [
    "erickt",
    "Nashenas88",
]
alumni = [
    "ComputerDruid",
    "djkoloski",
    "tmandry",
    "P1n3appl3",
]

[permissions]
bors.rust.try = true
