name = "goals"
subteam-of = "launching-pad"

[people]
leads = ["nikomatsakis"]
members = [
    "nikomatsakis",
    "joshtriplett",
    "lqd",
    "nandsh",
    "davidtwco",
    "traviscross",
    "spastorino",
]
alumni = [
]

[[github]]
team-name = "goals"
orgs = ["rust-lang"]

[rfcbot]
label = "T-goals"
name = "Goals"
ping = "rust-lang/goals"

[website]
name = "Goals team"
description = "Administering the Rust goal setting program"
email = "goals@rust-lang.org"
zulip-stream = "project goals"
repo = "https://github.com/rust-lang/rust-project-goals"

[[zulip-groups]]
name = "T-goals"
