name = "infra"
subteam-of = "operations"

[people]
leads = ["aidanhs"]
members = [
    "Mark-Simulacrum",
    "TimNN",
    "aidanhs",
    "alexcrichton",
    "ashleygwilliams",
    "erickt",
    "kennytm",
    "pietroalbini",
    "sgrif",
    "shepmaster",
]

[permissions]
perf = true
crater = true
bors.rust.review = true
bors.crater.review = true

[rfcbot]
label = "T-infra"
name = "Infrastructure"
ping = "rust-lang/infra"

[website]
name = "Infrastructure team"
description = "infrastructure supporting the Rust project itself: CI, releases, bots, metrics"
email = "infra@rust-lang.org"
discord-invite = "https://discord.gg/AxXmxzN"
discord-name = "#infra"

[[lists]]
address = "infra@rust-lang.org"

[[lists]]
address = "infra-team@rust-lang.org"

[[lists]]
address = "craterbot@rust-lang.org"

[[lists]]
address = "admin@rust-lang.org"
include-team-members = false
extra-people = [
    "aturon",
    "alexcrichton",
]

[[lists]]
address = "rust-key@rust-lang.org"
include-team-members = false
extra-people = [
    "aturon",
    "alexcrichton",
]

[[lists]]
address = "appveyor@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-ops@googlegroups.com",
]

[[lists]]
address = "appveyor-libs@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-ops@googlegroups.com",
]

[[lists]]
address = "bors@rust-lang.org"
include-team-members = false
extra-people = [
    "alexcrichton",
]

[[lists]]
address = "crates-io-cert@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-ops@googlegroups.com",
]

[[lists]]
address = "dmarc-rua@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-ops@googlegroups.com",
]

[[lists]]
address = "docker-hub-rustci@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-ops@googlegroups.com",
]
