name = "infra"
subteam-of = "operations"

[people]
leads = ["aidanhs", "pietroalbini"]
members = [
    "Mark-Simulacrum",
    "aidanhs",
    "kennytm",
    "nellshamrell",
    "pietroalbini",
    "sgrif",
    "shepmaster",
]

[[github]]
orgs = ["rust-lang", "rust-lang-ci", "rust-lang-nursery"]

[[github]]
team-name = "rust-infra"
orgs = ["bors-rs"]

[permissions]
perf = true
crater = true
bors.rust.review = true
bors.crater.review = true

[rfcbot]
label = "T-infra"
name = "Infrastructure"
ping = "rust-lang/infra"

[website]
name = "Infrastructure team"
description = "Managing the infrastructure supporting the Rust project itself, including CI, releases, bots, and metrics"
email = "infra@rust-lang.org"
zulip-stream = "t-infra"

[[lists]]
address = "infra@rust-lang.org"

[[lists]]
address = "infra-team@rust-lang.org"

[[lists]]
address = "craterbot@rust-lang.org"
