name = "infra-admins"

[people]
leads = []
members = [
    "Mark-Simulacrum",
    "pietroalbini",
    "jdno",
]

[permissions]
sync-team-confirmation = true

[[lists]]
address = "admin@rust-lang.org"

[[lists]]
address = "admin@crates.io"

[[lists]]
address = "rust-key@rust-lang.org"

[[lists]]
address = "appveyor@rust-lang.org"

[[lists]]
address = "appveyor-libs@rust-lang.org"

[[lists]]
address = "bors@rust-lang.org"

[[lists]]
address = "crates-io-cert@rust-lang.org"

[[lists]]
address = "dmarc-rua@rust-lang.org"

[[lists]]
address = "docker-hub-rustci@rust-lang.org"

[[lists]]
address = "google-admin@rust-lang.org"
