name = "infra"
top-level = true

[people]
leads = ["shepmaster", "jdno"]
members = [
    "Mark-Simulacrum",
    "kennytm",
    "pietroalbini",
    "shepmaster",
    "jdno",
    "Kobzol",
    "MarcoIeni",
]
alumni = [
    "alexcrichton",
    "aturon",
    "brson",
    "sgrif",
    "nellshamrell",
    "ashleygwilliams",
    "aidanhs",
    "jyn514",
    "TimNN",
    "erickt",
    "frewsxcv",
    "tomprince",
    "carols10cents",
    "rylev",
]

[[github]]
orgs = ["rust-lang", "rust-lang-ci", "rust-lang-nursery"]

[[github]]
team-name = "rust-infra"
orgs = ["bors-rs"]

[permissions]
perf = true
crater = true
dev-desktop = true
bors.rust.review = true
bors.bors-kindergarten.review = true

[rfcbot]
label = "T-infra"
name = "Infrastructure"
ping = "rust-lang/infra"

[website]
name = "Infrastructure team"
description = "Managing the infrastructure supporting the Rust project itself, including CI, releases, bots, and metrics"
email = "infra@rust-lang.org"
zulip-stream = "t-infra"
repo = "https://github.com/rust-lang/infra-team"

[[lists]]
address = "infra@rust-lang.org"

[[lists]]
address = "infra-team@rust-lang.org"

[[lists]]
address = "craterbot@rust-lang.org"

[[zulip-groups]]
name = "T-infra"
