name = "lang"

[people]
leads = ["nikomatsakis"]
members = [
    "Centril",
    "aturon",
    "cramertj",
    "eddyb",
    "joshtriplett",
    "nikomatsakis",
    "pnkfelix",
    "scottmcm",
    "withoutboats",
]

[permissions]
perf = true
bors.rust.review = true

[rfcbot]
label = "T-lang"
name = "Language"
ping = "rust-lang/lang"

[website]
name = "Language team"
description = "designing new language features"
repo = "http://github.com/rust-lang/lang-team"

[[lists]]
address = "lang-private@rust-lang.org"

[[lists]]
address = "lang@rust-lang.org"
extra-teams = ["lang-shepherds"]

[[lists]]
address = "language-design-team@rust-lang.org"
extra-teams = ["lang-shepherds"]
