name = "lang-docs"
subteam-of = "lang"

[people]
leads = ["ehuss", "traviscross"]
members = [
    "ehuss",
    "JohnTitor",
    "traviscross",
]
alumni = [
    "Centril",
    "Gankra",
    "Havvy",
    "matthewjasper",
]

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[website]
name = "lang-docs team"
description = "Developing and writing the docs related to the lang team"
zulip-stream = "t-lang/doc"
