name = "lang"

[people]
leads = ["nikomatsakis", "joshtriplett"]
members = [
    "cramertj",
    "joshtriplett",
    "nikomatsakis",
    "pnkfelix",
    "scottmcm",
    "withoutboats",
]
alumni = [
    "Centril",
]

[permissions]
perf = true
crater = true
bors.rust.review = true

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[rfcbot]
label = "T-lang"
name = "Language"
ping = "rust-lang/lang"

[website]
name = "Language team"
description = "Designing and helping to implement new language features"
repo = "http://github.com/rust-lang/lang-team"

[[lists]]
address = "lang-private@rust-lang.org"

[[lists]]
address = "lang@rust-lang.org"

[[lists]]
address = "language-design-team@rust-lang.org"
