name = "leadership-council"

[people]
leads = []
members = [
    "carols10cents",
    "eholk",
    "ehuss",
    "jackh726",
    "jonathanpallant",
    "Mark-Simulacrum",
    "m-ou-se",
    "rylev",
]
alumni = [
    "khionu",
]

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[rfcbot]
label = "T-leadership-council"
name = "Leadership Council"
ping = "rust-lang/leadership-council"

[website]
name = "Leadership council"
description = "Charged with the success of the Rust Project as whole, consisting of representatives from top-level teams"
email = "council@rust-lang.org"
zulip-stream = "council"
weight = 1000
repo = "https://github.com/rust-lang/leadership-council"

[[lists]]
address = "council@rust-lang.org"

[[zulip-groups]]
name = "council"
