name = "libc"
subteam-of = "libs"

[people]
leads = []
members = [
    "JohnTitor",
    "joshtriplett",
    "m-ou-se",
    "Amanieu",
]

[permissions]
bors.libc.review = true

[[github]]
orgs = ["rust-lang"]

[website]
name = "Libc crate team"
description = "Developing and maintaining the libc crate"
repo = "https://github.com/rust-lang/libc"
