name = "library-reviewers"
subteam-of = "libs"

[people]
leads = []
members = [
    "cramertj",
    "dtolnay",
    "joshtriplett",
    "kennytm",
    "KodrAus",
    "m-ou-se",
    "Mark-Simulacrum",
    "sfackler",
    "shepmaster",
    "workingjubilee",
    "JohnTitor",
]
alumni = [
    "withoutboats",
]

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[permissions]
perf = true
crater = true
bors.rust.review = true

[website]
name = "Library reviewers"
description = "Developing and reviewing changes to the Rust standard library"
