name = "libs"

[people]
leads = []
members = [
    "Amanieu",
    "BurntSushi",
    "KodrAus",
    "SimonSapin",
    "dtolnay",
    "sfackler",
    "withoutboats",
    "LukasKalbertodt",
    "m-ou-se",
]

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[permissions]
perf = true
crater = true
bors.rust.review = true
bors.hashbrown.review = true
bors.libc.review = true
bors.stdarch.review = true

[rfcbot]
label = "T-libs"
name = "Libraries"
ping = "rust-lang/libs"
exclude-members = [
    "LukasKalbertodt",
    "SimonSapin",
]

[website]
page = "library"
name = "Library team"
description = "Developing and managing the Rust standard library, official rust-lang crates, code conventions, and ecosystem support"
zulip-stream = "t-libs"

[[lists]]
address = "libs-private@rust-lang.org"

[[lists]]
address = "libs@rust-lang.org"

[[lists]]
address = "library-team@rust-lang.org"
