name = "libs"

[people]
leads = ["m-ou-se"]
members = [
  "Amanieu",
  "m-ou-se",
  "joshtriplett",
  "yaahc",
  "cuviper",
  "the8472",
]

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[permissions]
perf = true
crater = true
bors.hashbrown.review = true
bors.libc.review = true
bors.rust.review = true
bors.stdarch.review = true

[rfcbot]
label = "T-libs"
name = "Library"
ping = "rust-lang/libs"

[website]
page = "library"
name = "Library team"
description = "Managing and maintaining the Rust standard library and official rust-lang crates"
zulip-stream = "t-libs"

[[lists]]
address = "libs-private@rust-lang.org"

[[lists]]
address = "libs@rust-lang.org"

[[lists]]
address = "library-team@rust-lang.org"

[[zulip-groups]]
name = "T-libs"
