name = "libs-api"
subteam-of = "libs"

[people]
leads = []
members = [
    "Amanieu",
    "BurntSushi",
    "dtolnay",
    "m-ou-se",
    "joshtriplett",
    "the8472",
]
alumni = [
    "alexcrichton",
    "aturon",
    "brson",
    "Gankra",
    "huonw",
    "Kimundi",
    "KodrAus",
    "LukasKalbertodt",
    "sfackler",
    "withoutboats",
    "SimonSapin",
    "yaahc",
]

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[permissions]
perf = true
crater = true
bors.rust.review = true

[rfcbot]
label = "T-libs-api"
name = "Library API"
ping = "rust-lang/libs-api"

[website]
weight = 100
name = "Library API team"
description = "Designing and maintaining the standard library API and guarding its stability"

[[lists]]
address = "libs-api@rust-lang.org"

[[zulip-groups]]
name = "T-libs-api"
