name = "libs-contributors"
subteam-of = "libs"

[people]
leads = []
members = [
    "cramertj",
    "dtolnay",
    "JohnTitor",
    "kennytm",
    "KodrAus",
    "Mark-Simulacrum",
    "SimonSapin",
    "workingjubilee",
    "ChrisDenton",
    "sunfishcode",
    "yaahc",
    "Noratrieb",
    "jhpratt",
    "joboet",
    "calebzulawski", # std::simd
    "tgross35",
    "ibraheemdev",
]
alumni = [
    "shepmaster",
]

[permissions]
bors.rust.review = true
crater = true
dev-desktop = true
perf = true

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[website]
weight = -100
name = "Library contributors"
description = "Contributing to the Rust standard library on a regular basis"
