name = "loongarch"
kind = "marker-team"

[people]
leads = []
members = [
    "heiher",
    "xiangzhai",
    "xen0n",
    "xry111",
    "your_name_here", # Don't forget to run `cargo run add-person` if you're new!
]
