name = "miri"
subteam-of = "compiler"

[people]
leads = ["RalfJung", "oli-obk"]
members = ["RalfJung", "oli-obk", "saethlin"]
alumni = ["solson"]

[permissions]
bors.miri.review = true

[website]
name = "Miri"
description = "Designing and implementing the Miri interpreter"
repo = "https://github.com/rust-lang/miri"

[[github]]
orgs = ["rust-lang"]

[[zulip-groups]]
name = "T-miri"
