name = "mods-venue"
subteam-of = "mods"

[people]
leads = []
members = [
    "oli-obk",
    "steffahn",
    "rylev",
    "Nadrieril",
    "jieyouxu",
    "rylev",
    "Noratrieb",
    "apiraino",
]
alumni = [
]

[[github]]
team-name = "mods"
orgs = ["rust-lang", "rust-lang-nursery"]

[website]
name = "Venue moderators"
description = "Moderating rust-lang github repositories and the rust-lang zulip"

[[zulip-groups]]
name = "T-mods-venue"
