name = "mods-discord"
subteam-of = "mods"

[people]
leads = []
members = [
    "fmoko",
    "Centril",
    "khionu",
    "sgrif",
    "technetos",
    "pietroalbini",
]

[website]
name = "Discord moderators"
description = "Moderating the Discord server"

[[lists]]
address = "discord-mods@rust-lang.org"
