name = "mods-discord"
subteam-of = "mods"

[people]
leads = []
members = [
    "khionu",
    "sgrif",
    "technetos",
    "Manishearth"
]
alumni = [
    "Centril",
    "diannasoreil",
]

[website]
name = "Discord moderators"
description = "Moderating the Discord server"

[[lists]]
address = "discord-mods@rust-lang.org"

[[discord-roles]]
name = "mods"
color = "#e74c3c"
