name = "mods-discord"
subteam-of = "mods"

[people]
leads = []
members = [
    "sgrif",
    "technetos",
    "Manishearth",
]
alumni = [
    "Centril",
    "manyinsects",
    "khionu",
    "pietroalbini",
]

[website]
name = "Discord moderators"
description = "Moderating the Discord server"

[[lists]]
address = "discord-mods@rust-lang.org"

[[discord-roles]]
name = "mods"
color = "#e74c3c"

[[github]]
orgs = ["rust-lang"]
