name = "project-dyn-upcasting"
kind = "project-group"
subteam-of = "lang"

[people]
leads = [
    "crlf0710",
]
members = [
    "crlf0710",
    "nikomatsakis",
]

[website]
name = "Dyn Upcasting Initiative"
description = "Extending Rust with Impl Trait"
repo = "https://github.com/rust-lang/dyn-upcasting-coercion-initiative"

[[github]]
orgs = ["rust-lang"]
team-name = "dyn-upcasting"
