name = "project-portable-simd"
kind = "project-group"
subteam-of = "libs"

[people]
leads = [
    "workingjubilee",
]
members = [
    "BurntSushi",
    "calebzulawski",
    "hsivonen",
    "programmerjake",
    "vertexclique",
    "workingjubilee",
]
alumni = ["Lokathor"]

[website]
name = "Portable SIMD Project Group"
description = "Adding portable SIMD to the standard library"

[[github]]
orgs = ["rust-lang"]
