name = "project-portable-simd"
kind = "project-group"
subteam-of = "libs"

[people]
leads = [
    "Lokathor",
    "workingjubilee",
]
members = [
    "BurntSushi",
    "calebzulawski",
    "KodrAus",
    "hsivonen",
    "Lokathor",
    "vertexclique",
    "workingjubilee",
]

[website]
name = "Portable SIMD Project Group"
description = "Adding portable SIMD to the standard library"

[[github]]
orgs = ["rust-lang"]
