name = "project-vision-doc-2025"
kind = "project-group"
subteam-of = "launching-pad"

[people]
leads = ["nikomatsakis", "jackh726"]
members = [
    "nikomatsakis",
    "jackh726",
    "ernestkissiedu",
    "timClicks",
    "PLeVasseur",
]
alumni = [
    "baumanj",
    "joshtriplett",
    "Nadrieril",
    "spastorino",
    "traviscross",
    "workingjubilee",
]

[[github]]
team-name = "project-vision-doc-2025"
orgs = ["rust-lang"]

[website]
name = "Vision doc"
description = "Authoring the Rust 2025 Vision doc"
zulip-stream = "vision-doc-2025"
repo = "https://github.com/rust-lang/vision-doc-2025"

[[lists]]
address = "project-vision-doc-2025@rust-lang.org"
