name = "project-exploit-mitigations"
kind = "project-group"
subteam-of = "compiler"

[people]
leads = [
    "rcvalle",
]
members = [
    "cuviper",
    "rcvalle",
]

[website]
name = "Exploit Mitigations Project Group"
description = "Maintaining and improving the existing, implementing, and researching new exploit mitigations for the Rust compiler"
repo = "https://github.com/rust-lang/project-exploit-mitigations"
zulip-stream = "project-exploit-mitigations"

[[github]]
orgs = ["rust-lang"]

[[zulip-groups]]
name = "project-exploit-mitigations"
