name = "release"

[people]
leads = ["Mark-Simulacrum"]
members = [
    "cuviper",
    "Dylan-DPC",
    "Mark-Simulacrum",
    "pietroalbini",
    "tmandry",
]
alumni = [
    "BatmanAoD",
    "Centril",
    "sgrif",
    "jonas-schievink",
    "XAMPPRocky",
]

[permissions]
crater = true
perf = true
bors.rust.review = true

[[github]]
orgs = ["rust-lang"]

[rfcbot]
label = "T-release"
name = "Release"
ping = "rust-lang/release"

[website]
name = "Release team"
description = "Tracking regressions and stabilizations, and producing Rust releases"
email = "release@rust-lang.org"
zulip-stream = "t-release"

[[lists]]
address = "release@rust-lang.org"

[[zulip-groups]]
name = "T-release"
