name = "release"
subteam-of = "operations"

[people]
leads = ["Mark-Simulacrum"]
members = [
    "BatmanAoD",
    "Centril",
    "cuviper",
    "Dylan-DPC",
    "Mark-Simulacrum",
    "pietroalbini",
    "sgrif",
    "jonas-schievink",
    "XAMPPRocky",
]

[permissions]
crater = true
perf = true
bors.rust.review = true

[github]
orgs = ["rust-lang"]

[rfcbot]
label = "T-release"
name = "Release"
ping = "rust-lang/release"

[website]
name = "Release team"
description = "tracking regressions, stabilizations, and producing Rust releases"
email = "release@rust-lang.org"
discord-invite = "https://discord.gg/pVTkgpv"
discord-name = "#release"

[[lists]]
address = "release@rust-lang.org"
