name = "rust-analyzer"
subteam-of = "compiler"

[people]
leads = ["Veykril"]
members = [
    "davidbarsky",
    "flodiebold",
    "HKalbasi",
    "lnicola",
    "Veykril",
    "ChayimFriedman2",
    "ShoyuVanilla",
]
alumni = [
    "edwin0cheng",
    "lowr",
    "matklad",
    "SomeoneToIgnore",
]

[website]
name = "rust-analyzer team"
description = "Rust IDE support and error-resilient compiler front-end"
zulip-stream = "t-compiler/rust-analyzer"
repo = "https://github.com/rust-lang/rust-analyzer"

[permissions]
bors.rust.review = true

[[github]]
orgs = ["rust-lang", "rust-analyzer"]

[[zulip-groups]]
name = "T-rust-analyzer"
