name = "rustdoc"
subteam-of = "devtools"

[people]
leads = ["GuillaumeGomez"]
members = [
    "GuillaumeGomez",
    "QuietMisdreavus",
    "ollie27",
    "kinnison",
]

[github]
orgs = ["rust-lang", "rust-lang-nursery"]

[permissions]
crater = true
bors.rust.review = true

[rfcbot]
label = "T-rustdoc"
name = "Rustdoc"
ping = "rust-lang/rustdoc"

[website]
name = "Rustdoc team"
description = "Rustdoc, the documentation tool"
discord-invite = "https://discord.gg/4yEYPuT"
discord-name = "#rustdoc"

[[lists]]
address = "rustdoc@rust-lang.org"
