name = "rust-for-linux"
kind = "marker-team"

[people]
leads = []
members = [
    "alex",
    "bjorn3",
    "Darksonn",
    "dingxiangfei2009",
    "fbq",
    "maurer",
    "metaspace",
    "nbdd0121",
    "ojeda",
    "tgross35",
    "vincenzopalazzo",
    "wedsonaf",
    "y86-dev",
]

[permissions]
bors.rust.try = true
