name = "rustdoc"
subteam-of = "devtools"

[people]
leads = ["GuillaumeGomez"]
members = [
    "GuillaumeGomez",
    "Manishearth",
    "Nemo157",
    "camelid",
    "jsha",
    "notriddle",
    "aDotInTheVoid",
]
alumni = [
    "jyn514",
    "kinnison",
    "ollie27",
    "CraftSpider",
]

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[permissions]
crater = true
bors.rust.review = true
perf = true

[rfcbot]
label = "T-rustdoc"
name = "Rustdoc"
ping = "rust-lang/rustdoc"

[website]
name = "Rustdoc team"
description = "Developing and managing the Rustdoc documentation tool"
zulip-stream = "rustdoc"

[[lists]]
address = "rustdoc@rust-lang.org"

[[zulip-groups]]
name = "T-rustdoc"
