name = "spec"
subteam-of = "lang"

[people]
leads = ["pnkfelix", "m-ou-se"]
members = [
    "pnkfelix",
    "m-ou-se",
    { name =  "JoelMarcey", roles = ["spec-editor"] },
    "ehuss",
]
alumni = []

[website]
name = "Specification team"
description = "Creating and maintaining the specification for the Rust language"
zulip-stream = "t-spec"
repo = "https://github.com/rust-lang/spec"

[[website.roles]]
id = "spec-editor"
description = "Editor"

[rfcbot]
label = "T-spec"
name = "Spec"
ping = "rust-lang/spec"

[[github]]
orgs = ["rust-lang"]

[[zulip-groups]]
name = "T-spec"
