name = "survey"
subteam-of = "launching-pad"

[people]
leads = ["Kobzol", "apiraino"]
members = ["graciegregory", "Kobzol", "apiraino"]
alumni = [
    "Manishearth",
    "nikomatsakis",
    "nrc",
    "sophiajt",
    "yaahc",
    "rylev",
]

[website]
name = "Survey team"
description = "Running, analysing, and presenting various Rust surveys"
repo = "https://github.com/rust-lang/surveys"

[[github]]
orgs = ["rust-lang"]

[[lists]]
address = "surveys@rust-lang.org"

[[lists]]
address = "survey-contributors@rust-lang.org"
