name = "triagebot"
subteam-of = "infra"

[people]
leads = ["Mark-Simulacrum"]
members = [
    "Mark-Simulacrum",
    "ehuss",
]
alumni = [
    "spastorino",
]

[[github]]
orgs = ["rust-lang"]

[website]
name = "Triagebot team"
description = "Maintaining and improving the rust-lang/triagebot tooling"
email = "triagebot@rust-lang.org"
zulip-stream = "triagebot"
repo = "https://github.com/rust-lang/triagebot"

[[lists]]
address = "triagebot@rust-lang.org"

[[zulip-groups]]
name = "T-triagebot"
