name = "twir"
subteam-of = "launching-pad"

[people]
leads = ["nellshamrell"]
members = [
    "nellshamrell",
    "llogiq",
    "cdmistman",
    "extrawurst",
    "andrewpollack",
    "JoelMarcey",
]
alumni = [
    "nasa42",
]

[[github]]
orgs = ["rust-lang"]

[[lists]]
address = "twir@rust-lang.org"
