name = "types"
# Really should be compiler + lang, but the team repo doesn't handle that
# right now
subteam-of = "compiler"

[people]
leads = ["nikomatsakis", "jackh726"]
members = [
    "aliemjay",
    "compiler-errors",
    "jackh726",
    "lcnr",
    "nikomatsakis",
    "oli-obk",
    "spastorino",
]
alumni = []

[website]
name = "Types team"
description = "Working to implement and formally define the semantics of the Rust language"
repo = "https://github.com/rust-lang/types-team"
zulip-stream = "t-types"

[rfcbot]
label = "T-types"
name = "Types"
ping = "rust-lang/types"

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[[zulip-groups]] 
name = "T-types"

[[zulip-groups]]
name = "T-types/meetings"
extra-people = ["eholk"]

[permissions]
bors.chalk.review = true
bors.rust.try = true
perf = true
crater = true
dev-desktop = true
