name = "wg-async-foundations"
wg = true

[people]
leads = ["nikomatsakis", "tmandry"]
members = [
  "nikomatsakis",
  "cramertj",
  "tmandry",
  "withoutboats",
  "gilescope",
  "csmoe",
  "Aaron1011",
]

[github]
orgs = ["rust-lang", "rust-lang-nursery"]

[website]
name = "Async foundations working group"
description = "Pursuing core language and library support for async-await"
repo = "https://github.com/rust-lang/wg-async-foundations"
