name = "wg-async"
kind = "working-group"

[people]
leads = ["nikomatsakis", "tmandry"]
members = [
  "eholk",
  "estebank",
  "guswynn",
  "michaelwoerister",
  "nikomatsakis",
  "nrc",
  "pnkfelix",
  "spastorino",
  "taiki-e",
  "tmandry",
  "yoshuawuyts",
]
alumni = [
  "Aaron1011",
  "LucioFranco",
  "bIgBV",
  "betamos",
  "cramertj",
  "csmoe",
  "doc-jones",
  "eminence",
  "emmanuelantony2000",
  "gilescope",
  "lbernick",
  "nellshamrell",
  "rylev",
  "withoutboats",
  "zeenix",
]

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[website]
name = "Async working group"
description = "Pursuing core language and library support for async-await"
repo = "https://github.com/rust-lang/wg-async"
zulip-stream = "wg-async"

[[zulip-groups]]
name = "WG-async"

[[zulip-groups]]
name = "WG-async-sprint-planning"
