name = "wg-async-foundations"
kind = "working-group"

[people]
leads = ["nikomatsakis", "tmandry"]
members = [
  "Aaron1011",
  "betamos",
  "bIgBV",
  "LucioFranco",
  "cramertj",
  "csmoe",
  "doc-jones",
  "eholk",
  "eminence",
  "emmanuelantony2000",
  "gilescope",
  "lbernick",
  "nellshamrell",
  "nikomatsakis",
  "rylev",
  "taiki-e",
  "tmandry",
  "yoshuawuyts",
  "zeenix",
]
alumni = [
  "withoutboats",
]

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[website]
name = "Async Foundations working group"
description = "Pursuing core language and library support for async-await"
repo = "https://github.com/rust-lang/wg-async-foundations"
zulip-stream = "wg-async-foundations"
