name = "wg-bindgen"
subteam-of = "devtools"
kind = "working-group"

[people]
leads = ["emilio", "fitzgen"]
members = [
    "emilio",
    "fitzgen",
]

[website]
name = "Bindgen working group"
description = "Developing tools for generating FFI bindings"
repo = "https://github.com/rust-lang-nursery/rust-bindgen"
discord-invite = "https://discord.gg/kgujzMR"
discord-name = "#wg-bindgen"
