name = "wg-cli"
wg = true

[people]
leads = []
members = [
    "codesections",
    "Dylan-DPC",
    "epage",
    "killercup",
    "matthiasbeyer",
    "spacekookie",
    "XAMPPRocky",
    "yoshuawuyts",
]

[website]
page = "cli"
name = "Command-line interfaces (CLI) working group"
description = "Focusing on the end-to-end experience of writing CLI apps, both large and small, in Rust."
discord-invite = "https://discord.gg/BXCBYX6"
discord-name = "#wg-cli"
