name = "wg-compiler-performance"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["Mark-Simulacrum"]
members = [
    "wesleywiser",
    "Mark-Simulacrum",
    "rylev"
]

[[github]]
orgs = ["rust-lang"]

[website]
name = "Compiler performance working group"
description = "Improving rustc compilation performance (build times)"

[permissions]
perf = true
bors.rust.try = true
