name = "wg-cli"
wg = true

[people]
leads = ["spacekookie"]
members = [
    "Dylan-DPC",
    "codesections",
    "epage",
    "killercup",
    "matthiasbeyer",
    "spacekookie",
    "yoshuawuyts",
    "deg4uss3r",
]

[website]
page = "cli"
name = "Command-line interfaces (CLI) working group"
description = "Focusing on the end-to-end experience of writing terminal apps, both large and small, in Rust."

[[lists]]
address = "cli-wg@rust-lang.org"

extra-emails = [
    "mail@r0tty.org",
    "msarfati@protonmail.com",
    "mail+rust-wg-cli@pksunkara.com",
    "Ricky@Hosfelt.io",
    "mail@beyermatthias.de",
]
