name = "wg-const-eval"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["oli-obk", "RalfJung"]
members = [
    "ecstatic-morse",
    "oli-obk",
    "RalfJung",
]

[website]
name = "Compile-time Function Evaluation Working Group"
description = "Soundly expanding the capabilities of compile-time function evaluation in Rust"
repo = "https://github.com/rust-lang/const-eval"

[[github]]
orgs = ["rust-lang"]
