name = "wg-cli"
subteam-of = "launching-pad"
kind = "working-group"

[people]
leads = ["epage"]
members = [
    "Dylan-DPC",
    "codesections",
    "epage",
    "matthiasbeyer",
    "deg4uss3r",
    "pksunkara",
]
alumni = [
    "killercup",
    "spacekookie",
    "yoshuawuyts",
]

[website]
page = "cli"
name = "Command-line interfaces (CLI) working group"
description = "Focusing on the end-to-end experience of writing terminal apps, both large and small, in Rust."
zulip-stream = "wg-cli"

[[lists]]
address = "cli-wg@rust-lang.org"

extra-emails = [
    "mail@r0tty.org",
    "msarfati@protonmail.com",
    "Ricky@Hosfe.lt",
    "mail@beyermatthias.de",
]
