name = "wg-embedded-resources"
subteam-of = "wg-embedded"
kind = "working-group"

[people]
leads = []
members = [
    "adamgreig",
    "andre-richter",
    "eldruin",
    "hargoniX",
    "jamesmunns",
    "therealprof",
]

[website]
name = "Embedded resources working group"
description = "Managing various resources owned by the embedded working group"

[[github]]
orgs = ["rust-embedded"]
team-name = "resources"
