name = "wg-embedded"
wg = true

[people]
leads = ["japaric", "therealprof", "jamesmunns"]
members = [
    "adamgreig",
    "almindor",
    "andre-richter",
    "awygle",
    "bradjc",
    "burrbull",
    "cr1901",
    "danc86",
    "Disasm",
    "dvc94ch",
    "dylanmckay",
    "Emilgardis",
    "eldruin",
    "hannobraun",
    "ithinuel",
    "jamesmunns",
    "japaric",
    "jcsoo",
    "jonas-schievink",
    "korken89",
    "laanwj",
    "nastevens",
    "paoloteti",
    "parched",
    "pftbest",
    "posborne",
    "raw-bin",
    "reitermarkus",
    "ryankurte",
    "sekineh",
    "thalesfragoso",
    "thejpster",
    "therealprof",
    "v-thakkar",
    "wizofe",
]

[website]
page = "embedded"
name = "Embedded devices working group"
description = "Focusing on improving the end-to-end experience of using Rust in resource-constrained environments and non-traditional platforms"
repo = "https://github.com/rust-embedded/wg"

[[lists]]
address = "embedded-wg@rust-lang.org"
