name = "wg-embedded-arm"
subteam-of = "wg-embedded"
kind = "working-group"

[people]
leads = []
members = [
    "adamgreig",
    "berkus",
    "ithinuel",
    "jonathanpallant",
    "nchong-at-aws",
    "newAM",
    "raw-bin",
    "robamu",
    "thalesfragoso",
    "therealprof",
]
alumni = [
    "andre-richter",
]

[website]
name = "Embedded Arm team"
description = "Develops and maintains the core of the Arm crate ecosystem"

[[github]]
orgs = ["rust-embedded"]
team-name = "Arm"
