name = "wg-embedded-riscv"
subteam-of = "wg-embedded"
kind = "working-group"

[people]
leads = []
members = [
    "Disasm",
    "almindor",
    "dkhayes117",
    "romancardenas",
]

[website]
name = "Embedded RISCV team"
description = "Develops and maintains the core of the embedded RISCV crate ecosystem"

[[github]]
orgs = ["rust-embedded"]
team-name = "risc-v"
