name = "wg-embedded-tools"
subteam-of = "wg-embedded"
kind = "working-group"

[people]
leads = []
members = [
    "adamgreig",
    "ryankurte",
    "thejpster",
    "reitermarkus",
    "Emilgardis",
    "burrbull",
    "therealprof",
    "jonathanpallant",
]

[website]
name = "Embedded Tools Team"
description = "Develops and maintains core embedded tools"

[[github]]
orgs = ["rust-embedded"]
team-name = "tools"
