name = "wg-embedded-libs"
subteam-of = "wg-embedded"
kind = "working-group"

[people]
leads = []
members = [
    "Dirbaio",
    "newAM",
    "reitermarkus",
    "zeenix",
]
alumni = []

[website]
name = "Embedded libraries team"
description = "Develops and maintains libraries for embedded devices"

[[github]]
orgs = ["rust-embedded"]
team-name = "libs"
