name = "wg-ffi-unwind"
subteam-of = "lang"
kind = "working-group"

[people]
leads = ["nikomatsakis", "acfoltzer", "BatmanAoD"]
members = [
    "Amanieu",
    "BatmanAoD",
    "CAD97",
    "acfoltzer",
    "bjorn3",
    "gnzlbg",
    "nbdd0121",
    "nikomatsakis",
    "joshtriplett",
]

[website]
name = "ffi-unwind project group"
description = "A working-group project to extend the Rust language to support unwinding that crosses FFI boundaries"
repo = "https://github.com/rust-lang/project-ffi-unwind"
zulip-stream = "project-ffi-unwind"

[[github]]
orgs = ["rust-lang"]

[[zulip-groups]]
name = "WG-ffi-unwind"
