name = "wg-governance"
subteam-of = "core"
kind = "working-group"

[[github]]
orgs = ["rust-lang"]

[people]
leads = ["XAMPPRocky", "nikomatsakis"]
members = [
    "BatmanAoD",
    "Manishearth",
    "XAMPPRocky",
    "gnunicorn",
    "nellshamrell",
    "nikomatsakis",
    "valgrimm",
]
alumni = [
    "skade",
]

[[lists]]
address = "governance@rust-lang.org"
extra-people = []

[website]
name = "Governance working group"
description = "Managing and improving Rust team governance"
repo = "https://github.com/rust-lang/wg-governance"
zulip-stream = "wg-governance"
