name = "wg-grammar"
subteam-of = "lang"
wg = true

[people]
leads = ["eddyb", "qmx"]
members = [
    "eddyb",
    "CAD97",
    "Centril",
    "qmx",
]

[website]
name = "Grammar"
description = "Working out the official, formal grammar for Rust and validating it against existing implementations."
