name = "wg-incr-comp"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["pnkfelix", "spastorino"]
members = ["davidtwco", "pnkfelix", "spastorino", "wesleywiser"]

[[github]]
orgs = ["rust-lang"]

[website]
name = "Incremental compilation working group"
description = "Fixing bugs, adding features and improving incremental compilation in rustc"
repo = "https://rust-lang.github.io/compiler-team/working-groups/incr-comp/"
zulip-stream = "t-compiler/wg-incr-comp"
