name = "wg-leads"
kind = "marker-team"

[people]
leads = []
members = []
included-teams = ["project-group-leads"]
include-wg-leads = true

[[lists]]
address = "wg-leads@rust-lang.org"
extra-teams = ["core"]
