name = "wg-llvm"
subteam-of = "compiler"
wg = true

[people]
leads = ["nagisa"]
members = ["nagisa"]

[[github]]
orgs = ["rust-lang"]

[website]
name = "LLVM working group"
description = "Working with LLVM upstream to represent Rust in its development"
repo = "https://rust-lang.github.io/compiler-team/working-groups/llvm/"
