name = "wg-meta"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["nikomatsakis", "davidtwco", "spastorino"]
members = ["nikomatsakis", "davidtwco", "spastorino"]

[website]
name = "Meta working group"
description = "Organizing and managing the Rust compiler team"
repo = "https://rust-lang.github.io/compiler-team/working-groups/meta/"
