name = "wg-nll"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["nikomatsakis", "pnkfelix"]
members = ["nikomatsakis", "pnkfelix", "davidtwco", "spastorino", "matthewjasper", "lqd"]

[website]
name = "Non-Lexical Lifetimes (NLL) working group"
description = "Implementing the new MIR-based borrow checker and non-lexical lifetimes in Rust"
repo = "https://rust-lang.github.io/compiler-team/working-groups/nll/"
zulip-stream = "t-compiler/wg-nll"
