name = "wg-parallel-rustc"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["cjgillot"]
members = [
    "cjgillot",
    "SparrowLii",
    "nnethercote",
    "bjorn3",
    "Kobzol",
]
alumni = [
    "Zoxc",
    "nikomatsakis",
    "Mark-Simulacrum",
    "alexcrichton",
    "cuviper",
    "spastorino",
]

[permissions]
bors.rust.try = true
perf = true

[website]
name = "Parallel rustc working group"
description = "Making parallel compilation the default for rustc"
repo = "https://rust-lang.github.io/compiler-team/working-groups/parallel-rustc/"
zulip-stream = "t-compiler/wg-parallel-rustc"

[[zulip-groups]]
name = "WG-parallel-rustc"
