name = "wg-rfc-2229"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["nikomatsakis", "matthewjasper"]
members = [
        "nikomatsakis",
        "matthewjasper",
        "arora-aman",
        "Azhng",
        "ChrisPardy",
        "jenniferwills",
        "logmosier",
        "null-sleep",
        "roxelo"
]

[[github]]
orgs = ["rust-lang"]

[website]
name = "RFC 2229 working group"
description = "Improving the behavior of closure-capture, and improving the documentation on closures"
repo = "https://rust-lang.github.io/compiler-team/working-groups/rfc-2229/"
