name = "wg-rustc-dev-guide"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["BoxyUwU", "tshepang"]
members = [
    "BoxyUwU",
    "JohnTitor",
    "camelid",
    "jieyouxu",
    "jyn514",
    "spastorino",
    "tshepang",
]
alumni = [
    "LeSeulArtichaut",
    "Nashenas88",
    "amanjeev",
    "chrissimpkins",
    "igaray",
    "mark-i-m",
    "pierwill",
    "rylev",
    "togiberlin",
]

[[github]]
orgs = ["rust-lang"]

[website]
name = "Rustc Dev Guide working area"
description = "Making the compiler easier to learn by maintaining and improving the Rustc Dev Guide"
repo = "https://forge.rust-lang.org/compiler/working-areas.html"
zulip-stream = "t-compiler/rustc-dev-guide"

[[zulip-groups]]
name = "WG-rustc-dev-guide"
