name = "wg-rustc-dev-guide"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["JohnTitor", "spastorino"]
members = [
    "JohnTitor",
    "camelid",
    "igaray",
    "spastorino",
    "tshepang",
]
alumni = ["LeSeulArtichaut", "Nashenas88", "amanjeev", "chrissimpkins", "jyn514", "mark-i-m", "rylev", "togiberlin", "pierwill"]
    

[[github]]
orgs = ["rust-lang"]

[website]
name = "Rustc Dev Guide working group"
description = "Making the compiler easier to learn by maintaining and improving the Rustc Dev Guide"
repo = "https://rust-lang.github.io/compiler-team/working-groups/rustc-dev-guide/"
zulip-stream = "t-compiler/wg-rustc-dev-guide"

[[zulip-groups]]
name = "WG-rustc-dev-guide"
