name = "wg-rustc-dev-guide"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["spastorino", "JohnTitor"]
members = [
    "spastorino",
    "amanjeev",
    "togiberlin",
    "JohnTitor",
    "chrissimpkins",
    "camelid",
    "igaray",
    "rylev",
    "pierwill",
    "tshepang",
]
alumni = ["LeSeulArtichaut", "jyn514", "mark-i-m", "Nashenas88"]

[[github]]
orgs = ["rust-lang"]

[website]
name = "Rustc Dev Guide working group"
description = "Making the compiler easier to learn by maintaining and improving the Rustc Dev Guide"
repo = "https://rust-lang.github.io/compiler-team/working-groups/rustc-dev-guide/"
zulip-stream = "t-compiler/wg-rustc-dev-guide"
