name = "wg-rust-by-example"
kind = "working-group"

[people]
leads = ["marioidival"]
members = [
    "marioidival",
]

alumni = [
    "steveklabnik",
]

[[github]]
orgs = ["rust-lang"]

[website]
name = "Rust by Example working group"
description = "Maintaining and updating the official Rust by Example book"
repo = "https://github.com/rust-lang/rust-by-example"
