name = "wg-rustfix"
subteam-of = "devtools"
kind = "working-group"

[people]
leads = []
members = [
    "Manishearth",
    "estebank",
    "killercup",
    "oli-obk",
    "phansch",
    "pietroalbini",
]

[website]
name = "Rustfix working group"
description = "Developing cargo-fix and serving as a point of contact for other teams"
discord-invite = "https://discord.gg/e6Q3cvu"
discord-name = "#wg-rustfix"
repo = "https://github.com/rust-lang/rustfix"
