name = "wg-self-profile"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["michaelwoerister", "wesleywiser"]
members = ["michaelwoerister", "wesleywiser"]

[permissions]
perf = true

[website]
name = "Self-profile working group"
description = "Improving the -Z self-profile feature of the Rust compiler"
repo = "https://rust-lang.github.io/compiler-team/working-groups/self-profile/"
