name = "wg-security-response"
subteam-of = "launching-pad"
kind = "working-group"

[people]
leads = []
members = [
    "cuviper",
    "pietroalbini",
    "Manishearth",
]
alumni = [
    "alexcrichton",
    "nikomatsakis",
    "steveklabnik",
]

[[github]]
team-name = "security"
orgs = ["rust-lang"]

[website]
name = "Security Response WG"
description = "Triaging and responding to incoming vulnerability reports"
email = "security@rust-lang.org"
repo = "https://github.com/rust-lang/wg-security-response"

[[lists]]
address = "security@rust-lang.org"

[[discord-roles]]
name = "security"
color = "#e91e63"

[[zulip-groups]]
name = "WG-security-response"
