name = "wg-triage"
subteam-of = "release"
kind = "working-group"

[people]
leads = ["Dylan-DPC"]
members = [
    "Dylan-DPC",
    "JohnTitor",
    "joelpalmer",
    "JohnCSimon",
    "edmilsonefs",
    "Alexendoo",
    "bstrie",
    "crlf0710",
    "Muirrum",
    "LeSeulArtichaut",
    "camelid",
]

[website]
name = "Triage working group"
description = "Triaging repositories under the rust-lang organisation"
zulip-stream = "t-release/triage"

[[github]]
orgs = ["rust-lang"]
