name = "wg-traits"
subteam-of = "compiler"
wg = true

[people]
leads = ["nikomatsakis"]
members = ["nikomatsakis", "jackh726", "detrumi", "skinny121", "yaahc"]

[website]
name = "Traits working group"
description = "Revamping the rustc trait implementation to follow the Chalk approach"
repo = "https://rust-lang.github.io/compiler-team/working-groups/traits/"

[github]
orgs = ["rust-lang", "rust-lang-nursery"]
