name = "wg-triage"
kind = "working-group"
subteam-of = "launching-pad"

[people]
leads = ["Dylan-DPC"]
members = [
    "Dylan-DPC",
    "JohnTitor",
    "joelpalmer",
    "JohnCSimon",
    "edmilsonefs",
    "Alexendoo",
    "bstrie",
    "crlf0710",
    "Muirrum",
    "camelid",
    "alice-i-cecile",
    "pitaj",
    "anden3",
    "KittyBorgX",
    "Enselic",
    "tranquillity-codes",
    "jieyouxu",
    "oskgo",
    "lolbinarycat",
    "alex-semenyuk",
    "LFS6502",
    "gstjepan2"
]
alumni = []

[website]
name = "Triage working group"
description = "Triaging repositories under the rust-lang organisation"
zulip-stream = "t-release/triage"

[[github]]
orgs = ["rust-lang"]

[[zulip-groups]]
name = "WG-triage"
