name = "wg-wasm"
subteam-of = "launching-pad"
kind = "working-group"

[people]
leads = ["fitzgen"]
members = [
    "fitzgen",
]

alumni = [
    "alexcrichton",
    "ashleygwilliams",
    "aturon",
    "yoshuawuyts",
]

[[lists]]
address = "wasm@rust-lang.org"
extra-people = [
    "alexcrichton",
    "aturon",
]

[website]
page = "wasm"
name = "WebAssembly (WASM) working group"
description = "Improving on the end-to-end experience of embedding Rust code in JS libraries and apps via WebAssembly"
