name = "wg-wasm"
wg = true

[people]
leads = ["fitzgen"]
members = [
    "fitzgen",
]

[[lists]]
address = "wasm@rust-lang.org"
extra-people = [
    "alexcrichton",
    "aturon",
    "mgattozzi",
]

[website]
page = "wasm"
name = "WebAssembly (WASM) working group"
description = "Focusing on the end-to-end experience of embedding Rust code in JS libraries and apps via WebAssembly."
