name = "windows"
kind = "marker-team"

[people]
leads = []
members = [
    "albertlarsan68",
    "arlosi",
    "danielframpton",
    "gdr-at-ms",
    "kennykerr",
    "luqmana",
    "lzybkr",
    "retep998",
    "rylev",
    "sivadeilra",
    "nico-abram",
    "wesleywiser",
    "ChrisDenton",
]
