[package]
name = "rust-team"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>", "Pietro Albini <pietro@pietroalbini.org>"]
edition = '2018'

[dependencies]
toml = "0.5.1"
failure = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
log = "0.4"
env_logger = { version = "0.5", default-features = false }
structopt = "0.2.13"
regex = "1.0.6"
rust_team_data = { path = "rust_team_data", features = ["email-encryption"] }
indexmap = "1.0.2"
reqwest = "0.9.18"
base64 = "0.10.1"
dialoguer = "0.7.1"

[dev-dependencies]
duct = "0.13.4"
atty = "0.2.14"
ansi_term = "0.12.1"
difference = "2.0.0"
walkdir = "2.3.1"

[workspace]
members = [
    "rust_team_data"
]
