allowed-mailing-lists-domains = [
    "rust-lang.org",
    "crates.io",
    "docs.rs",
    "rust-embedded.org",
    "rustconf.com",
]

allowed-github-orgs = [
    "bors-rs",
    "rust-lang",
    "rust-lang-ci",
    "rust-lang-nursery",
    "rust-dev-tools",
    "rust-embedded",
]

permissions-bors-repos = [
    "cargo",
    "chalk",
    "clippy",
    "compiler-builtins",
    "crater",
    "crates-io",
    "hashbrown",
    "miri",
    "libc",
    "regex",
    "rls",
    "rust",
    "rustlings",
    "rustup-rs",
    "semverver",
    "stdarch",
    "team",
    "vscode-rust",
]

permissions-bools = [
    "perf",
    "crater",
]

permissions-crates-io-ops-bot-apps = [
    "crates-io",
    "staging-crates-io",
]
