allowed-mailing-lists-domains = [
    "rust-lang.org",
    "crates.io",
    "docs.rs",
    "rust-embedded.org",
    "rustconf.com",
]

allowed-github-orgs = [
    "rust-lang",
    "rust-lang-nursery",
    "rust-lang-deprecated",
    "rust-dev-tools",
    "rust-embedded",
    "rust-analyzer",
]

# GitHub organizations where member management is independent
# and should not be automatically synchronized
independent-github-orgs = [
    "rust-embedded",
]

permissions-bors-repos = [
    "bors-kindergarten",
    "rust",
]

permissions-bools = [
    "perf",
    "crater",
    "crates-io-admin",
    "dev-desktop",
    "sync-team-confirmation",
]

# GitHub accounts that are allowed to stay in the GitHub organizations,
# even if they may not be members of any team.
# Note: Infra admins are automatically included from the infra-admins team.
special-org-members = [
    # Bots.
    "bors",
    "craterbot",
    "rfcbot",
    "rust-rfcbot",
    "rust-embedded-bot",
    "rust-heroku-deploy-access",
    "rust-highfive",
    "rust-lang-core-team-agenda-bot",
    "rust-lang-glacier-bot",
    "rust-lang-owner",
    "rust-log-analyzer",
    "rust-timer",
    "rustbot",
    # Ferrous systems employees who manage the github sponsors
    # for rust-analyzer.
    "MissHolmes",
    "skade",
]

members-without-zulip-id = [
    "arshiamufti",
    "bnchi",
    "brotzeit",
    "celaus",
    "chris-morgan",
    "codesections",
    "da-x",
    "ecstatic-morse",
    "gdr-at-ms",
    "kennykerr",
    "mathk",
    "nico-abram",
    "opeolluwa",
    "patchfx",
    "pvdrz",
    "reitermarkus",
    "ryankurte",
    "Stammark",
    "therealprof",
    "zeenix"
]

enable-rulesets-repos = [
   "rust-lang/bors"
]
