# All mailing lists managed on Mailgun.
#
# This file is synchronized to configuration on Mailgun via Travis whenever a
# commit is pushed to master. Travis just runs `cargo run` for this. The
# configuration for this file is one top-level key, `lists`, which is an array
# of mailing lists.
#
# Each mailing list has three keys:
#
#   * `address` - the email address of this mailing list (including the domain)
#   * `access_level` - one of the following:
#       * `readonly` - only authenticated users can post
#       * `members` - only members can post to the list
#       * `everyone` - anyone can post to the list
#   * `members` - an array of email addresses to forward mail to
#
# All mailing lists behave the same way. When an email is received it then
# broadcasts the email to all users of the mailing list.
#
#
# Current list of domains you can choose from:
#
#   * rustlang.com
#   * rustlang.net

[[lists]]
address = 'admin@crates.io'
access_level = 'everyone'
members = [
  'admin@rust-lang.org',
]

[[lists]]
address = 'legal@crates.io'
access_level = 'everyone'
members = [
  'core-team@rust-lang.org',
]

[[lists]]
address = 'help@crates.io'
access_level = 'everyone'
members = [
  'crates-io@rust-lang.org',
]

[[lists]]
address = 'admin@rust-lang.org'
access_level = 'everyone'
members = [
  "alex@crichton.co",
  "aturon@mozilla.com",
]

[[lists]]
address = 'all@rust-lang.org'
access_level = 'everyone'
members = [
  "community@rust-lang.org",
  "compiler@rust-lang.org",
  "core@rust-lang.org",
  "lang@rust-lang.org",
  "libs@rust-lang.org",
  "dev-tools@rust-lang.org",
  "docs@rust-lang.org",
  "infra@rust-lang.org",
  "release@rust-lang.org",
]

[[lists]]
address = 'appveyor-libs@rust-lang.org'
access_level = 'everyone'
members = [
  "rust-ops@googlegroups.com",
]

[[lists]]
address = 'appveyor@rust-lang.org'
access_level = 'everyone'
members = [
  "rust-ops@googlegroups.com",
]

[[lists]]
address = 'bors@rust-lang.org'
access_level = 'everyone'
members = [
  "acrichton@mozilla.com",
]

[[lists]]
address = 'cargo@rust-lang.org'
access_level = 'everyone'
members = [
  "acrichton@mozilla.com",
  "wycats@gmail.com",
  "woboats@gmail.com",
  "josh@joshtriplett.org",
  "ncameron@mozilla.com",
  "eric@huss.org",
  "eh2406@wayne.edu",
  "dale.wijnand@gmail.com",
]

[[lists]]
address = 'community-team@rust-lang.org'
access_level = 'everyone'
members = [
  "community@rust-lang.org",
]

[[lists]]
address = 'community@rust-lang.org'
access_level = 'everyone'
members = [
  "rust-community@googlegroups.com",
  "manishsmail@gmail.com",
  "booyaabooyaabooyaa@gmail.com",
  "janerik@fnordig.de",
  "ashley@integer32.com",
  "olivia@fastmail.com",
  "mrgould93@gmail.com",
  "amufti16@gmail.com",
  "parry.wilcox@gmail.com",
  "kookie@spacekookie.de",
  "flo@andersground.net",
  "rust@flaki.hu",
  "mattgathu@gmail.com",
  "celaus@gmail.com",
  "wes@wezm.net",
  "varma.sunjay@gmail.com",
]

[[lists]]
address = 'compiler-team@rust-lang.org'
access_level = 'everyone'
members = [
  "compiler@rust-lang.org",
]

[[lists]]
address = 'compiler@rust-lang.org'
access_level = 'everyone'
members = [
  "ariel.byd@gmail.com",
  "nrc@mozilla.com",
  "pnkfelix@mozilla.com",
  "edy.burt@gmail.com",
  "nmatsakis@mozilla.com",
  "michaelwoerister@gmail.com",
  "jeffrey.seyfried@gmail.com",
  "vadim.petrochenkov@gmail.com",
  "esteban@kuber.com.ar",
  "zoxc32@gmail.com",
  "cramertaylorj@gmail.com",
  "simonas+t-compiler@kazlauskas.me",
  "github@varkor.com",
]

[[lists]]
address = 'core-team@rust-lang.org'
access_level = 'everyone'
members = [
  "core@rust-lang.org",
]

[[lists]]
address = 'core@rust-lang.org'
access_level = 'everyone'
members = [
  "acrichton@mozilla.com",
  "wycats@gmail.com",
  "steve@steveklabnik.com",
  "aturon@mozilla.com",
  "nmatsakis@mozilla.com",
  "erick.tryzelaar@gmail.com",
  "nrc@mozilla.com",
  "carol.nichols@gmail.com",
  "mark.simulacrum@gmail.com",
  "ashley666ashley@gmail.com",
  "aidanhs@cantab.net",
]

[[lists]]
address = 'craterbot@rust-lang.org'
access_level = 'everyone'
members = [
  "infra@rust-lang.org",
]

[[lists]]
address = 'crates-io-cert@rust-lang.org'
access_level = 'everyone'
members = [
  "rust-ops@googlegroups.com",
]

[[lists]]
address = 'crates-io@rust-lang.org'
access_level = 'everyone'
members = [
  "ashley@integer32.com",
  "carol.nichols@gmail.com",
  "acrichton@mozilla.com",
  "sean@seantheprogrammer.com",
]

[[lists]]
address = 'dev-tools@rust-lang.org'
access_level = 'everyone'
members = [
  "woboats@gmail.com",
  "manishsmail@gmail.com",
  "steve@steveklabnik.com",
  "nfitzgerald@mozilla.com",
  "japaricious@gmail.com",
  "killercup@gmail.com",
  "ncameron@mozilla.com",
]

[[lists]]
address = 'dmarc-rua@rust-lang.org'
access_level = 'everyone'
members = [
  "rust-ops@googlegroups.com",
]

[[lists]]
address = 'doc-team@rust-lang.org'
access_level = 'everyone'
members = [
  "docs@rust-lang.org",
]

[[lists]]
address = 'docker-hub-rustci@rust-lang.org'
access_level = 'everyone'
members = [
  "rust-ops@googlegroups.com",
]

[[lists]]
address = 'docs@rust-lang.org'
access_level = 'everyone'
members = [
  "steve@steveklabnik.com",
  "guillaume1.gomez@gmail.com",
  "grey@quietmisdreavus.net",
  "coreyf@rwell.org",
  "oprojektir@gmail.com",
  "ryan.havvy@gmail.com",
  "alercah@gmail.com",
]

[[lists]]
address = 'ecosystem@rust-lang.org'
access_level = 'everyone'
members = [
  "ashleymannix@live.com.au",
  "woboats@gmail.com",
  "sfackler@gmail.com",
  "aturon@mozilla.com",
]

[[lists]]
address = 'editors@rust-lang.org'
access_level = 'everyone'
members = [
  "ides@rust-lang.org",
]

[[lists]]
address = 'embedded-wg@rust-lang.org'
access_level = 'everyone'
members = [
  "david@craven.ch",
  "hanno@braun-robotics.com",
  "james.munns@gmail.com",
  "jcsoo@bobbin.io",
  "jorge@japaric.io",
  "jp@thejpster.org.uk",
  "me@dylanmckay.io",
  "pftbest@gmail.com",
]

[[lists]]
address = 'ides@rust-lang.org'
access_level = 'everyone'
members = [
  "beskvlad@gmail.com",
  "alexheretic@gmail.com",
  "jase.williams@gmail.com",
  "autozimu@gmail.com",
  "lbullen@redhat.com",
  "aleksey.kladov@gmail.com",
  "xanewok@gmail.com",
  "ncameron@mozilla.com",
]

[[lists]]
address = 'infra-team@rust-lang.org'
access_level = 'everyone'
members = [
  "infra@rust-lang.org",
]

[[lists]]
address = 'infra@rust-lang.org'
access_level = 'everyone'
members = [
  "erick.tryzelaar@gmail.com",
  "mail@timnn.me",
  "jake.goulding@gmail.com",
  "acrichton@mozilla.com",
  "aidanhs@cantab.net",
  "mark.simulacrum@gmail.com",
  "aturon@mozilla.com",
  "kennytm@gmail.com",
  "ashley@integer32.com",
  "sean@seantheprogrammer.com",
  "pietro@pietroalbini.org",
]

[[lists]]
address = 'lang-private@rust-lang.org'
access_level = 'everyone'
members = [
  "nmatsakis@mozilla.com",
  "nrc@mozilla.com",
  "pnkfelix@mozilla.com",
  "aturon@mozilla.com",
  "edy.burt@gmail.com",
  "woboats@gmail.com",
  "cramertaylorj@gmail.com",
  "josh@joshtriplett.org",
  "smcmurray@acm.org",
  "twingoow@gmail.com",
]

[[lists]]
address = 'lang@rust-lang.org'
access_level = 'everyone'
members = [
  "lang-private@rust-lang.org",
  "scott@solson.me",
  "whitequark@whitequark.org",
]

[[lists]]
address = 'language-design-team@rust-lang.org'
access_level = 'everyone'
members = [
  "lang@rust-lang.org",
]

[[lists]]
address = 'leads@rust-lang.org'
access_level = 'everyone'
members = [
  "wg-leads@rust-lang.org",
  "aturon@mozilla.com",
  "ashley@integer32.com",
  "nmatsakis@mozilla.com",
  "nrc@mozilla.com",
  "aidanhs@cantab.net",
  "mark.simulacrum@gmail.com",
  "steve@steveklabnik.com",
]

[[lists]]
address = 'library-team@rust-lang.org'
access_level = 'everyone'
members = [
  "libs@rust-lang.org",
]

[[lists]]
address = 'libs-private@rust-lang.org'
access_level = 'everyone'
members = [
  "acrichton@mozilla.com",
  "aturon@mozilla.com",
  "sfackler@gmail.com",
  "jamslam@gmail.com",
  "loebel.marvin@gmail.com",
  "dtolnay@gmail.com",
  "ssapin@mozilla.com",
]

[[lists]]
address = 'libs@rust-lang.org'
access_level = 'everyone'
members = [
  "acrichton@mozilla.com",
  "aturon@mozilla.com",
  "sfackler@gmail.com",
  "jamslam@gmail.com",
  "loebel.marvin@gmail.com",
  "dtolnay@gmail.com",
  "ashleymannix@live.com.au",
  "woboats@gmail.com",
  "ssapin@mozilla.com",
]

[[lists]]
address = 'net@rust-lang.org'
access_level = 'everyone'
members = [
  "aturon@mozilla.com",
  "mark.simulacrum@gmail.com",
  "bob@cloudflare.com",
  "mail@josefbrandl.de",
  "tinagma@gmail.com",
  "coleman.mcfarland@gmail.com",
  "aidanhs@cantab.net",
  "dbarsky@amazon.com",
  "inejge@gmail.com",
  "bhargav.voleti93@gmail.com",
  "azdle@azdle.net",
  "yoshuawuyts@gmail.com",
  "aajtodd@gmail.com",
  "sfackler@gmail.com",
  "hello@stephanbuys.com",
  "wg-net@nemo157.com",
  "gruberbastian@me.com",
  "jsgf@fb.com",
  "mail@jakub-kozlowski.com",
  "michaeljkillough@gmail.com",
  "sloretan@gmail.com",
  "ashfordneil0@gmail.com",
  "a@tj.id.au",
  "yarnnd@gmail.com",
  "eric@reichertconsulting.com",
  "karimair@gmail.com",
  "flo@andersground.net",
  "rolf@zxcv.nl",
  "jbcden@gmail.com",
  "me@kleimkuhler.com",
  "pierre.krieger1708@gmail.com",
  "etryzelaar@google.com",
  "contact@geoffroycouprie.com",
  "eric@dattore.me",
  "service@maksims.co",
  "sriram@tinverse.com",
  "yusuke.sasaki.nuem@gmail.com",
  "ricky@hosfelt.io",
  "alberto@albertocoscia.me",
  "kulshrax@gmail.com",
  "alec@mocatta.net",
  "xenith@xenith.org",
  "arve.knudsen@gmail.com",
  "ben.e.saunders@gmail.com",
  "pickfire@riseup.net",
  "lkurusa@kernelstuff.org",
  "armin.ronacher@active-4.com",
]

[[lists]]
address = 'production@rust-lang.org'
access_level = 'everyone'
members = [
  "aidanhs@cantab.net",
  "nrc@mozilla.com",
  "claus.matzinger@gmail.com",
  "aturon@mozilla.com",
]

[[lists]]
address = 'reach@rust-lang.org'
access_level = 'everyone'
members = [
  "ashley@integer32.com",
  "carol.nichols@integer32.com",
  "dhosfelt@mozilla.com",
  "aidanhs@cantab.net",
]

[[lists]]
address = 'release@rust-lang.org'
access_level = 'everyone'
members = [
  "mark.simulacrum@gmail.com",
  "sertac.olgunsoylu@gmail.com",
  "justplayyeh@gmail.com",
  "cuviper@gmail.com",
  "trevorreiff@gmail.com",
  "joe@unicornclouds.com",
  "theaaronepower@gmail.com",
  "pramodpsb@hotmail.com",
  "cssivision@gmail.com",
  "araz@abishov.com",
  "pietro@pietroalbini.org",
  "dyxushuai@gmail.com",
  "batmanaod@gmail.com",
  "adrianquiroga@outlook.com",
  "hanquang@outlook.com",
  "sean@seantheprogrammer.com",
]

[[lists]]
address = 'rust-2018@rust-lang.org'
access_level = 'everyone'
members = [
  "acrichton@mozilla.com",
  "nmatsakis@mozilla.com",
  "nrc@mozilla.com",
  "ashley@integer32.com",
  "mark.simulacrum@gmail.com",
  "twingoow@gmail.com",
  "mail@oli-obk.de",
  "killercup@gmail.com",
  "steve@steveklabnik.com",
  "japaricious@gmail.com",
  "fitzgen@mozilla.com",
  "aturon@mozilla.com",
]

[[lists]]
address = 'rust-dev-tools@rust-lang.org'
access_level = 'everyone'
members = [
  "dev-tools@rust-lang.org",
]

[[lists]]
address = 'rust-icci@rust-lang.org'
access_level = 'everyone'
members = [
  "mwoerister@mozilla.com",
]

[[lists]]
address = 'rust-key@rust-lang.org'
access_level = 'everyone'
members = [
  "acrichton@mozilla.com",
  "aturon@mozilla.com",
]

[[lists]]
address = 'rust-mods@rust-lang.org'
access_level = 'everyone'
members = [
  "rust-mods@googlegroups.com",
]

[[lists]]
address = 'rustbridge@rust-lang.org'
access_level = 'everyone'
members = [
  "ashley@integer32.com",
  "amufti16@gmail.com",
]

[[lists]]
address = 'rustdoc@rust-lang.org'
access_level = 'everyone'
members = [
  "grey@quietmisdreavus.net",
  "steve@steveklabnik.com",
  "guillaume1.gomez@gmail.com",
  "olliemail27@gmail.com",
  "onuraslan@gmail.com",
]

[[lists]]
address = 'security@rust-lang.org'
access_level = 'everyone'
members = [
  "acrichton@mozilla.com",
  "nmatsakis@mozilla.com",
  "steve@steveklabnik.com",
  "wycats@gmail.com",
]

[[lists]]
address = 'style-team@rust-lang.org'
access_level = 'everyone'
members = [
  "scott@solson.me",
  "josh@joshtriplett.org",
  "japaricious@gmail.com",
  "steve@steveklabnik.com",
  "npmazzuca@gmail.com",
  "ncameron@mozilla.com",
]

[[lists]]
address = 'team@rust-lang.org'
access_level = 'everyone'
members = [
  "all@rust-lang.org",
]

[[lists]]
address = 'tools-team@rust-lang.org'
access_level = 'everyone'
members = [
  "dev-tools@rust-lang.org",
]

[[lists]]
address = 'trademark@rust-lang.org'
access_level = 'everyone'
members = [
  "aturon@mozilla.com",
  "nmatsakis@mozilla.com",
]

[[lists]]
address = 'twir@rust-lang.org'
access_level = 'everyone'
members = [
  "bogusandre@gmail.com",
  "vikrant@webstream.io",
]

[[lists]]
address = 'underhanded@rust-lang.org'
access_level = 'everyone'
members = [
  "rust-underhanded@googlegroups.com",
]

[[lists]]
address = 'user-logos@rust-lang.org'
access_level = 'everyone'
members = [
  "acrichton@mozilla.com",
  "wycats@gmail.com",
  "steve@steveklabnik.com",
  "dbau.pp@gmail.com",
  "aturon@mozilla.com",
  "nmatsakis@mozilla.com",
]

[[lists]]
address = 'verification@rust-lang.org'
access_level = 'everyone'
members = [
  "rust-verification@googlegroups.com",
]

[[lists]]
address = 'wasm@rust-lang.org'
access_level = 'everyone'
members = [
  "acrichto@mozilla.com",
  "aturon@mozilla.com",
  "mgattozzi@gmail.com",
]

[[lists]]
address = 'wg-leads@rust-lang.org'
access_level = 'everyone'
members = [
  "cramertaylorj@gmail.com",
  "woboats@gmail.com",
  "killercup@gmail.com",
  "nfitzgerald@mozilla.com",
  "japaricious@gmail.com",
]
