org = "rust-lang"
name = "annotate-snippets-rs"
description = "Library for snippet annotations"
bots = ["renovate"]

[access.teams]
cargo = "write"
wg-diagnostics = "write"

[[branch-protections]]
pattern = "main"
ci-checks = ["CI"]
required-approvals = 0

[[crates-io-publishing]]
crates = ["annotate-snippets"]
workflow-filename = "release.yml"
environment = "publish"

[[environments]]
name = "publish"
