org = "rust-lang"
name = "ar_archive_writer"
description = "A writer for object file ar archives"
bots = []

[access.teams]
compiler = "write"

[[environments]]
name = "publish"

[[crates-io]]
crates = ["ar_archive_writer"]
publish-workflow = "publish.yml"
publish-environment = "publish"
