org = "rust-lang"
name = "bors"
description = "Rust implementation of bors used for various Rust components (e.g. the compiler)."
bots = ["rustbot"]

[access.teams]
infra = "write"
infra-bors = "write"
mods = "maintain"

[[branch-protections]]
pattern = "main"
ci-checks = ["Test", "Test Docker"]
required-approvals = 0
