org = "rust-lang"
name = "bors"
description = "Rust implementation of bors used for various Rust components (e.g. the compiler)."
bots = ["rustbot", "renovate"]

[access.teams]
infra = "write"
infra-bors = "write"
# For approving production deployments of bors
infra-admins = "write"
infra-bors-admins = "write"

[[branch-protections]]
pattern = "main"
ci-checks = ["Test", "Test Docker"]
required-approvals = 0

[environments.production]
branches = ["main"]

[environments.staging]
branches = ["main"]

