org = "rust-lang"
name = "bors"

description = "Rust implementation of bors used for various Rust components (e.g. the compiler)."
bots = ["triagebot"]

[access.teams]
infra = "write"
infra-bors = "write"
mods = "maintain"

[[branch]]
name = "main"
ci-checks = ["Test"]
