org = "rust-lang"
name = "cargo-bisect-rustc"
description = "Bisects rustc, either nightlies or CI artifacts"
homepage = "https://rust-lang.github.io/cargo-bisect-rustc/"
bots = []

[access.teams]
compiler = "write"

[access.individuals]
ehuss = "write"

[[branch-protections]]
pattern = "master"
required-approvals = 0

[[environments]]
name = "github-pages"


[[crates-io-publishing]]
crates = ["cargo-bisect-rustc"]
teams = []
