org = "rust-lang"
name = "cargo"
description = "The Rust package manager"
homepage = "https://doc.rust-lang.org/cargo"
bots = ["bors", "rustbot", "rfcbot"]

[access.teams]
cargo = "write"

[[branch-protections]]
pattern = "master"

[[branch-protections]]
pattern = "rust-1.*"
