org = "rust-lang"
name = "cargo"
description = "The Rust package manager"
homepage = "https://doc.rust-lang.org/cargo"
bots = ["rustbot", "rfcbot", "renovate"]

[access.teams]
cargo = "write"

[[branch-protections]]
pattern = "master"
ci-checks = ["conclusion"]

[[branch-protections]]
pattern = "rust-1.*"
ci-checks = ["conclusion"]

[[environments]]
name = "github-pages"

[[environments]]
name = "release"


[[crates-io-publishing]]
crates = ["cargo-credential-gnome-secret", "home"]
teams = []

[[crates-io-publishing]]
crates = ["build-rs", "cargo", "cargo-credential", "cargo-credential-1password", "cargo-credential-libsecret", "cargo-credential-macos-keychain", "cargo-credential-wincred", "cargo-platform", "cargo-test-macro", "cargo-test-support", "cargo-util", "cargo-util-schemas", "crates-io", "rustfix"]
teams = ["release-publishers"]
