org = 'rust-lang'
name = 'cc-rs'
description = 'Rust library for build scripts to compile C/C++ code into a Rust library'
homepage = "https://docs.rs/cc"
bots = []

[access.teams]
crate-maintainers = 'maintain'

[access.individuals]
NobodyXu = 'write'

[[branch-protections]]
pattern = 'main'
required-approvals = 0
