org = 'rust-lang'
name = 'cc-rs'
description = 'Rust library for build scripts to compile C/C++ code into a Rust library'
homepage = "https://docs.rs/cc"
bots = []

[access.teams]
crate-maintainers = 'maintain'

[[branch-protections]]
pattern = 'main'
required-approvals = 0
ci-checks = ['Tests pass']

[[crates-io-publishing]]
crates = ["cc", "find-msvc-tools"]
workflow-filename = "publish.yml"
environment = "publish"

[[environments]]
name = ""
