org = 'rust-lang'
name = 'cfg-if'
description = 'A if/elif-like macro for Rust #[cfg] statements'
bots = []

[access.teams]
crate-maintainers = 'maintain'

[[environments]]
name = "github-pages"


[[crates-io-publishing]]
crates = ["cfg-if"]
teams = ["libs"]
