org = "rust-lang"
name = "chalk"
description = "An implementation and definition of the Rust trait system using a PROLOG-like logic solver"
homepage = "https://rust-lang.github.io/chalk/book/"
bots = ["rustbot", "bors"]

[access.teams]
types = "write"
