org = "rust-lang"
name = "compiler-builtins"
description = "Rust implementations of compiler-rt and libm"
bots = []

[access.teams]
crate-maintainers = "maintain"

[[branch-protections]]
pattern = "main"
ci-checks = ["success"]
required-approvals = 0
