org = "rust-lang"
name = "crates.io"
description = "The Rust package registry"
homepage = "https://crates.io"
bots = ["renovate", "rustbot", "heroku-deploy-access"]

[access.teams]
crates-io = "write"

[[environments]]
name = ""
