org = "rust-lang"
name = "crates.io"
description = "The Rust package registry"
homepage = "https://crates.io"
bots = ["renovate", "rustbot", "heroku-deploy-access"]

[access.teams]
crates-io = "write"

[[branch-protections]]
pattern = "main"
ci-checks = [
    "Backend / Lint",
    "Backend / Test",
    "Frontend / Lint",
    "Frontend / Test",
    "Backend / dependencies",
]
required-approvals = 0
