org = "rust-lang"
name = "crates-io-auth-action"
description = "Get a crates.io temporary access token"
bots = []

[access.teams]
infra-admins = "write"
infra = "triage"

[[branch-protections]]
pattern = "main"
ci-checks = ["Conclusion"]
required-approvals = 0
