org = 'rust-lang'
name = 'docs.rs'
description = 'crates.io documentation generator'
homepage = "https://docs.rs"
bots = ["rustbot", "renovate"]

[access.teams]
docs-rs = 'write'
docs-rs-reviewers = 'write'

[[branch-protections]]
pattern = 'main'
required-approvals = 0
