org = "rust-lang"
name = "edition-guide"
description = "A guide to changes between various editions of Rust"
homepage = "https://doc.rust-lang.org/nightly/edition-guide/"
bots = ["rustbot", "rfcbot"]

[access.teams]
project-edition-2024 = "maintain"

[[branch-protections]]
pattern = "master"
ci-checks = ["Success gate"]
required-approvals = 0
