org = "rust-lang"
name = "effects-initiative"
description = "Public repository for the Rust effects initiative"
homepage = "https://rust-lang.github.io/keyword-generics-initiative/"
bots = []

[access.teams]
project-keyword-generics = "write"

[environments.github-pages]

