org = "rust-lang"
name = "fls"
description = "The FLS"
homepage = "https://rust-lang.github.io/fls"
bots = ["rustbot", "rfcbot"]

[access.teams]
fls = "write"
fls-contributors = "triage"
lang = "write"
lang-docs = "write"
lang-ops = "write"
spec = "write"
spec-contributors = "triage"

[[branch-protections]]
pattern = "main"
ci-checks = ["CI finished"]

[[environments]]
name = "github-pages"

