org = "rust-lang"
name = "glob"
description = "Support for matching file paths against Unix shell style patterns."
homepage = "https://doc.rust-lang.org/glob"
bots = ["rustbot"]

[access.teams]
crate-maintainers = "maintain"

[[branch-protections]]
pattern = "master"
ci-checks = ["success"]
required-approvals = 0

[[environments]]
name = ""
