org = "rust-lang"
name = "impl-trait-utils"
description = "Utilities for working with impl traits in Rust."
bots = []

[access.teams]
wg-async = "write"

[access.individuals]
compiler-errors = "maintain"
traviscross = "maintain"
tmandry = "maintain"

[[branch-protections]]
pattern = "main"
