org = 'rust-lang'
name = 'libm'
description = "A port of MUSL's libm to Rust."
bots = []

[access.teams]
crate-maintainers = 'maintain'

[[branch-protections]]
pattern = "master"
ci-checks = ['success']
required-approvals = 0
