org = 'rust-lang'
name = 'log'
description = 'Logging implementation for Rust'
homepage = "https://docs.rs/log"
bots = []

[access.teams]
crate-maintainers = 'maintain'

[access.individuals]
Thomasdezeeuw = 'maintain'

[[environments]]
name = "github-pages"


[[crates-io-publishing]]
crates = ["log"]
teams = ["log-owners", "libs"]
