org = "rust-lang"
name = "mdBook"
description = "Create book from markdown files. Like Gitbook but implemented in Rust"
homepage = "https://rust-lang.github.io/mdBook/"
bots = ["rustbot", "renovate"]

[access.teams]
devtools = "write"

[access.individuals]
# Dylan-DPC is maintaining mdbook along with ehuss. Planning to add a team
# soon, and then this can be removed.
Dylan-DPC = "write"

[[branch-protections]]
pattern = "master"
ci-checks = ["Success gate"]
required-approvals = 0

[[crates-io-publishing]]
crates = [
    "mdbook",
    "mdbook-core",
    "mdbook-driver",
    "mdbook-html",
    "mdbook-markdown",
    "mdbook-preprocessor",
    "mdbook-renderer",
    "mdbook-summary",
]
workflow-filename = "deploy.yml"
environment = "publish"

[[environments]]
name = "github-pages"

[[environments]]
name = "publish"

