org = "rust-lang"
name = "measureme"
description = "Support crate for rustc's self-profiling feature"
bots = []

[access.teams]
compiler = "write"

[[branch-protections]]
pattern = "master"
ci-checks = ["success"]

[[branch-protections]]
pattern = "stable"
ci-checks = ["success"]

[[crates-io]]
crates = ["analyzeme", "decodeme", "measureme"]
publish-workflow = "publish.yml"
publish-environment = "publish"

[environments.publish]
branches = ["master"]
tags = ["*"]

