org = "rust-lang"
name = "pkg-config-rs"
description = "Build library for invoking pkg-config for Rust"
homepage = "https://docs.rs/pkg-config"
bots = []

[access.teams]
crate-maintainers = "maintain"

[access.individuals]
sdroege = "write"

[[environments]]
name = "github-pages"


[[crates-io-publishing]]
crates = ["pkg-config"]
teams = []
