org = "rust-lang"
name = "portable-simd"
description = "The testing ground for the future of portable SIMD in Rust"
bots = ["rustbot"]

[access.teams]
project-portable-simd = "write"

[[branch-protections]]
pattern = "master"
required-approvals = 0

[environments.github-pages]

