org = "rust-lang"
name = "project-exploit-mitigations"
description = "Exploit Mitigations Project Group"
bots = []

[access.teams]
core = "admin"
mods = "maintain"
project-exploit-mitigations = "maintain"

[[branch-protections]]
pattern = "main"
dismiss-stale-review = true
