org = "rust-lang"
name = "reference"
description = "The Rust Reference"
homepage = "https://doc.rust-lang.org/nightly/reference/"
bots = ["rustbot"]

[access.teams]
lang = "write"
lang-docs = "write"
spec = "write"
spec-contributors = "write"

[[branch-protections]]
pattern = "master"
ci-checks = ["Test"]
