org = "rust-lang"
name = "rfcs"
description = "RFCs for changes to Rust"
homepage = "https://rust-lang.github.io/rfcs/"
bots = ["rustbot", "rfcbot"]

[access.teams]
all = "write"

[[branch-protections]]
pattern = "master"
