org = "rust-lang"
name = "rustc-perf"
description = "Website for graphing performance of rustc"
homepage = "https://perf.rust-lang.org"
bots = []

[access.teams]
wg-compiler-performance = "write"

[[branch-protections]]
pattern = "master"
ci-checks = [
    "Test and deploy",
    "Test on Windows",
    "Test benchmarks",
    "Test runtime benchmarks",
    "Database Check",
]
