org = "rust-lang"
name = "rust-analyzer"
description = "A Rust compiler front-end for IDEs"
homepage = "https://rust-analyzer.github.io/"
bots = ["rustbot"]

[access.teams]
rust-analyzer = "write"
rust-analyzer-contributors = "triage"

[[branch-protections]]
pattern = "master"
ci-checks = ["conclusion"]
required-approvals = 0
