org = "rust-lang"
name = "rustwide"
description = "Execute your code on the Rust ecosystem."
bots = []

[access.teams]
infra = "write"
docs-rs = "write"

[[crates-io-publishing]]
crates = ["rustwide"]
teams = ["infra"]
