org = "rust-lang"
name = "rust-by-example"
description = "Learn Rust with examples (Live code editor included)"
homepage = "https://doc.rust-lang.org/stable/rust-by-example/"
bots = ["rustbot"]

[access.teams]
wg-rust-by-example = "write"
