org = "rust-lang"
name = "rust-analyzer"
description = "A Rust compiler front-end for IDEs"
homepage = "https://rust-analyzer.github.io/"
bots = ["rustbot"]

[access.teams]
rust-analyzer = "write"
rust-analyzer-contributors = "triage"

[[branch-protections]]
pattern = "master"
ci-checks = ["conclusion"]
required-approvals = 0

[[environments]]
name = "github-pages"


[[crates-io-publishing]]
crates = ["ra_ap_edition", "ra_ap_intern", "ra_ap_load-cargo", "ra_ap_macros", "ra_ap_proc-macro-srv-cli", "ra_ap_query-group-macro", "ra_ap_span", "ra_ap_syntax-bridge"]
teams = []

[[crates-io-publishing]]
crates = ["ra_ap_base_db", "ra_ap_cfg", "ra_ap_hir", "ra_ap_hir_def", "ra_ap_hir_expand", "ra_ap_hir_ty", "ra_ap_ide", "ra_ap_ide_assists", "ra_ap_ide_completion", "ra_ap_ide_db", "ra_ap_ide_diagnostics", "ra_ap_ide_ssr", "ra_ap_limit", "ra_ap_mbe", "ra_ap_parser", "ra_ap_paths", "ra_ap_proc_macro_api", "ra_ap_proc_macro_srv", "ra_ap_profile", "ra_ap_project_model", "ra_ap_rust-analyzer", "ra_ap_stdx", "ra_ap_syntax", "ra_ap_test_utils", "ra_ap_text_edit", "ra_ap_toolchain", "ra_ap_tt", "ra_ap_vfs", "ra_ap_vfs-notify"]
teams = ["wg-rls-2"]
