org = 'rust-lang'
name = 'rust-forge'
description = 'Information useful to people contributing to Rust'
homepage = "https://forge.rust-lang.org/"
bots = ["rustbot"]

[access.teams]
community = "maintain"
compiler = "maintain"
content = "maintain"
crates-io = "maintain"
docs-rs = "maintain"
infra = "maintain"
internal-sites = "maintain"
lang = "maintain"
lang-ops = "maintain"
leadership-council = "maintain"
libs = "maintain"
libs-api = "maintain"
edition = "maintain"
release = "maintain"
rustdoc = "maintain"
triagebot = "maintain"
rustc-dev-guide = "maintain"

[[branch-protections]]
pattern = "master"
ci-checks = ["test"]

[[environments]]
name = "github-pages"

