org = "rust-lang"
name = "stdarch"
description = "Rust's standard library vendor-specific APIs and run-time feature detection"
homepage = "https://doc.rust-lang.org/stable/core/arch/"
bots = ["rustbot"]

[access.teams]
libs = "write"
libs-api = "write"
libs-contributors = "write"

[[branch-protections]]
pattern = "master"
ci-checks = ["conclusion"]
required-approvals = 0
