org = "rust-lang"
name = "surveys-private"
description = "A private repository for survey data that is only accessible to the survey working group (and admins)"
bots = []
private-non-synced = true

[access.teams]
community-survey = "maintain"
