org = "rust-lang"
name = "sync-team"
description = "Synchronize the team repository with the services we use"
bots = []

[access.teams]
infra = "write"
infra-admins = "maintain"

[[branch-protections]]
pattern = "master"
ci-checks = ["CI"]
allowed-merge-teams = ["infra-admins"]
