org = "rust-lang"
name = "team"
description = "Rust teams structure"
bots = []

[access.teams]
moderation = "write"
team-repo-admins = "write"
infra = "triage"

[[branch-protections]]
pattern = "master"
ci-checks = ["CI"]
dismiss-stale-review = true
