org = "rust-lang"
name = "team"
description = "Rust teams structure"
bots = []

[access.teams]
mods = "write"
team-repo-admins = "write"
infra = "triage"

[[branch-protections]]
pattern = "main"
ci-checks = ["CI"]
dismiss-stale-review = true

[environments.deploy]
branches = ["gh-readonly-queue/main/*", "main"]

[environments.github-pages]
branches = ["main"]

