org = "rust-lang"
name = "www.rust-lang.org"
description = "The home of the Rust website"
homepage = "https://www.rust-lang.org"
bots = ["rustbot"]

[access.teams]
website = "write"

[[branch-protections]]
pattern = "main"

[[environments]]
name = "github-pages"

[[environments]]
name = "new-rust-www"

[[environments]]
name = "rust-www-staging"

[[environments]]
name = "rust-www-try"

