name = "community-rustbridge"
subteam-of = "community"

[people]
leads = []
members = []

alumni = [
    "manyinsects",
    "technetos",
    "arshiamufti",
    "spacekookie",
    "sebasmagri",
    "mattgathu",
    "ashleygwilliams",
]

[website]
name = "RustBridge team"
description = "Helping to bring underrepresented groups into Rust"
repo = "https://github.com/rustbridge/team"

[[github]]
orgs = ["rust-lang"]
