name = "project-foundation"
kind = "project-group"
subteam-of = "core"

[people]
leads = []
members = []
alumni = [
    "Manishearth",
    "ashleygwilliams",
    "joshtriplett",
    "nellshamrell",
    "nikomatsakis",
    "emilyalbini",
    "rylev",
    "skade",
]

[website]
name = "Foundation Project Group"
description = "Explore, plan and create a foundation for the Rust project"
email = "foundation@rust-lang.org"

[[lists]]
address = "foundation@rust-lang.org"
include-team-members = false

[[lists]]
address = "foundation-moderation@rust-lang.org"
include-team-members = false

[[github]]
orgs = ["rust-lang"]
