name = "wg-net-async"
subteam-of = "wg-net"
kind = "working-group"

[people]
leads = ["cramertj", "MajorBreakfast"]
members = ["cramertj", "MajorBreakfast"]

[website]
name = "Async foundations working group"
description = "Stabilizing and documenting the async features of Rust"
discord-invite = "https://discord.gg/JebCvj5"
discord-name = "#wg-net-async"
